	.align 2
DirectSoundWaveData_86B5D04:: @ 86B5D04
	.incbin "sound/direct_sound_samples/86B5D04.bin"

	.align 2
DirectSoundWaveData_86B63A8:: @ 86B63A8
	.incbin "sound/direct_sound_samples/86B63A8.bin"

	.align 2
DirectSoundWaveData_86B6BA0:: @ 86B6BA0
	.incbin "sound/direct_sound_samples/86B6BA0.bin"

	.align 2
DirectSoundWaveData_86B776C:: @ 86B776C
	.incbin "sound/direct_sound_samples/86B776C.bin"

	.align 2
DirectSoundWaveData_86B86A4:: @ 86B86A4
	.incbin "sound/direct_sound_samples/86B86A4.bin"

	.align 2
DirectSoundWaveData_86B9318:: @ 86B9318
	.incbin "sound/direct_sound_samples/86B9318.bin"

	.align 2
DirectSoundWaveData_86BA7E8:: @ 86BA7E8
	.incbin "sound/direct_sound_samples/86BA7E8.bin"

	.align 2
DirectSoundWaveData_86BBE98:: @ 86BBE98
	.incbin "sound/direct_sound_samples/86BBE98.bin"

	.align 2
DirectSoundWaveData_86BD1DC:: @ 86BD1DC
	.incbin "sound/direct_sound_samples/86BD1DC.bin"

	.align 2
DirectSoundWaveData_86BDC80:: @ 86BDC80
	.incbin "sound/direct_sound_samples/86BDC80.bin"

	.align 2
DirectSoundWaveData_86BEF94:: @ 86BEF94
	.incbin "sound/direct_sound_samples/86BEF94.bin"

	.align 2
DirectSoundWaveData_86C2590:: @ 86C2590
	.incbin "sound/direct_sound_samples/86C2590.bin"

	.align 2
DirectSoundWaveData_86C2A68:: @ 86C2A68
	.incbin "sound/direct_sound_samples/86C2A68.bin"

	.align 2
DirectSoundWaveData_86C4344:: @ 86C4344
	.incbin "sound/direct_sound_samples/86C4344.bin"

	.align 2
DirectSoundWaveData_86C566C:: @ 86C566C
	.incbin "sound/direct_sound_samples/86C566C.bin"

	.align 2
DirectSoundWaveData_86C5B0C:: @ 86C5B0C
	.incbin "sound/direct_sound_samples/86C5B0C.bin"

	.align 2
DirectSoundWaveData_86C6200:: @ 86C6200
	.incbin "sound/direct_sound_samples/86C6200.bin"

	.align 2
DirectSoundWaveData_86C6A90:: @ 86C6A90
	.incbin "sound/direct_sound_samples/86C6A90.bin"

	.align 2
DirectSoundWaveData_86C7308:: @ 86C7308
	.incbin "sound/direct_sound_samples/86C7308.bin"

	.align 2
DirectSoundWaveData_86C8348:: @ 86C8348
	.incbin "sound/direct_sound_samples/86C8348.bin"

	.align 2
DirectSoundWaveData_86C875C:: @ 86C875C
	.incbin "sound/direct_sound_samples/86C875C.bin"

	.align 2
DirectSoundWaveData_86C958C:: @ 86C958C
	.incbin "sound/direct_sound_samples/86C958C.bin"

	.align 2
DirectSoundWaveData_86CA520:: @ 86CA520
	.incbin "sound/direct_sound_samples/86CA520.bin"

	.align 2
DirectSoundWaveData_86CADD4:: @ 86CADD4
	.incbin "sound/direct_sound_samples/86CADD4.bin"

	.align 2
DirectSoundWaveData_86CB6B8:: @ 86CB6B8
	.incbin "sound/direct_sound_samples/86CB6B8.bin"

	.align 2
DirectSoundWaveData_86CC5E4:: @ 86CC5E4
	.incbin "sound/direct_sound_samples/86CC5E4.bin"

	.align 2
DirectSoundWaveData_86CCAFC:: @ 86CCAFC
	.incbin "sound/direct_sound_samples/86CCAFC.bin"

	.align 2
DirectSoundWaveData_86CD0C4:: @ 86CD0C4
	.incbin "sound/direct_sound_samples/86CD0C4.bin"

	.align 2
DirectSoundWaveData_86CDFDC:: @ 86CDFDC
	.incbin "sound/direct_sound_samples/86CDFDC.bin"

	.align 2
DirectSoundWaveData_86CF950:: @ 86CF950
	.incbin "sound/direct_sound_samples/86CF950.bin"

	.align 2
DirectSoundWaveData_86D1A2C:: @ 86D1A2C
	.incbin "sound/direct_sound_samples/86D1A2C.bin"

	.align 2
DirectSoundWaveData_86D925C:: @ 86D925C
	.incbin "sound/direct_sound_samples/86D925C.bin"

	.align 2
DirectSoundWaveData_86D9C14:: @ 86D9C14
	.incbin "sound/direct_sound_samples/86D9C14.bin"

	.align 2
DirectSoundWaveData_86DAA94:: @ 86DAA94
	.incbin "sound/direct_sound_samples/86DAA94.bin"

	.align 2
DirectSoundWaveData_86DB908:: @ 86DB908
	.incbin "sound/direct_sound_samples/86DB908.bin"

	.align 2
DirectSoundWaveData_86DD11C:: @ 86DD11C
	.incbin "sound/direct_sound_samples/86DD11C.bin"

	.align 2
DirectSoundWaveData_86DE6C0:: @ 86DE6C0
	.incbin "sound/direct_sound_samples/86DE6C0.bin"

	.align 2
DirectSoundWaveData_86DFCA4:: @ 86DFCA4
	.incbin "sound/direct_sound_samples/86DFCA4.bin"

	.align 2
DirectSoundWaveData_86E0D98:: @ 86E0D98
	.incbin "sound/direct_sound_samples/86E0D98.bin"

	.align 2
DirectSoundWaveData_86E1CF8:: @ 86E1CF8
	.incbin "sound/direct_sound_samples/86E1CF8.bin"

	.align 2
DirectSoundWaveData_86E3358:: @ 86E3358
	.incbin "sound/direct_sound_samples/86E3358.bin"

	.align 2
DirectSoundWaveData_86E48B4:: @ 86E48B4
	.incbin "sound/direct_sound_samples/86E48B4.bin"

	.align 2
DirectSoundWaveData_86E5440:: @ 86E5440
	.incbin "sound/direct_sound_samples/86E5440.bin"

	.align 2
DirectSoundWaveData_86E89E4:: @ 86E89E4
	.incbin "sound/direct_sound_samples/86E89E4.bin"

	.align 2
DirectSoundWaveData_86EAD00:: @ 86EAD00
	.incbin "sound/direct_sound_samples/86EAD00.bin"

	.align 2
DirectSoundWaveData_86EE3CC:: @ 86EE3CC
	.incbin "sound/direct_sound_samples/86EE3CC.bin"

	.align 2
DirectSoundWaveData_86EF71C:: @ 86EF71C
	.incbin "sound/direct_sound_samples/86EF71C.bin"

	.align 2
DirectSoundWaveData_86F0C2C:: @ 86F0C2C
	.incbin "sound/direct_sound_samples/86F0C2C.bin"

	.align 2
DirectSoundWaveData_86F204C:: @ 86F204C
	.incbin "sound/direct_sound_samples/86F204C.bin"

	.align 2
DirectSoundWaveData_86F30E8:: @ 86F30E8
	.incbin "sound/direct_sound_samples/86F30E8.bin"

	.align 2
DirectSoundWaveData_86F4144:: @ 86F4144
	.incbin "sound/direct_sound_samples/86F4144.bin"

	.align 2
DirectSoundWaveData_86FB0D8:: @ 86FB0D8
	.incbin "sound/direct_sound_samples/86FB0D8.bin"

	.align 2
DirectSoundWaveData_86FF65C:: @ 86FF65C
	.incbin "sound/direct_sound_samples/86FF65C.bin"

	.align 2
DirectSoundWaveData_86FFDC0:: @ 86FFDC0
	.incbin "sound/direct_sound_samples/86FFDC0.bin"

	.align 2
DirectSoundWaveData_8701A10:: @ 8701A10
	.incbin "sound/direct_sound_samples/8701A10.bin"

	.align 2
DirectSoundWaveData_8703214:: @ 8703214
	.incbin "sound/direct_sound_samples/8703214.bin"

	.align 2
DirectSoundWaveData_8706DCC:: @ 8706DCC
	.incbin "sound/direct_sound_samples/8706DCC.bin"

	.align 2
DirectSoundWaveData_8709004:: @ 8709004
	.incbin "sound/direct_sound_samples/8709004.bin"

	.align 2
DirectSoundWaveData_870AE74:: @ 870AE74
	.incbin "sound/direct_sound_samples/870AE74.bin"

	.align 2
DirectSoundWaveData_870DE64:: @ 870DE64
	.incbin "sound/direct_sound_samples/870DE64.bin"

	.align 2
DirectSoundWaveData_8710AB8:: @ 8710AB8
	.incbin "sound/direct_sound_samples/8710AB8.bin"

	.align 2
DirectSoundWaveData_8715038:: @ 8715038
	.incbin "sound/direct_sound_samples/8715038.bin"

	.align 2
DirectSoundWaveData_8717980:: @ 8717980
	.incbin "sound/direct_sound_samples/8717980.bin"

	.align 2
DirectSoundWaveData_87190E0:: @ 87190E0
	.incbin "sound/direct_sound_samples/87190E0.bin"

	.align 2
DirectSoundWaveData_871A724:: @ 871A724
	.incbin "sound/direct_sound_samples/871A724.bin"

	.align 2
DirectSoundWaveData_871CBCC:: @ 871CBCC
	.incbin "sound/direct_sound_samples/871CBCC.bin"

	.align 2
DirectSoundWaveData_871F234:: @ 871F234
	.incbin "sound/direct_sound_samples/871F234.bin"

	.align 2
DirectSoundWaveData_87205DC:: @ 87205DC
	.incbin "sound/direct_sound_samples/87205DC.bin"

	.align 2
DirectSoundWaveData_8721AAC:: @ 8721AAC
	.incbin "sound/direct_sound_samples/8721AAC.bin"

	.align 2
DirectSoundWaveData_87224B8:: @ 87224B8
	.incbin "sound/direct_sound_samples/87224B8.bin"

	.align 2
DirectSoundWaveData_87240CC:: @ 87240CC
	.incbin "sound/direct_sound_samples/87240CC.bin"

	.align 2
DirectSoundWaveData_8725A2C:: @ 8725A2C
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_8726EF0:: @ 8726EF0
	.incbin "sound/direct_sound_samples/8726EF0.bin"

	.align 2
DirectSoundWaveData_872762C:: @ 872762C
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C:: @ 872921C
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0:: @ 872A5D0
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_872CC54:: @ 872CC54
	.incbin "sound/direct_sound_samples/872CC54.bin"

	.align 2
DirectSoundWaveData_872DE98:: @ 872DE98
	.incbin "sound/direct_sound_samples/872DE98.bin"

	.align 2
DirectSoundWaveData_872EEA8:: @ 872EEA8
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0:: @ 87301B0
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_87322BC:: @ 87322BC
	.incbin "sound/direct_sound_samples/87322BC.bin"

	.align 2
DirectSoundWaveData_8734298:: @ 8734298
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8:: @ 87364A8
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_8736C74:: @ 8736C74
	.incbin "sound/direct_sound_samples/8736C74.bin"

	.align 2
DirectSoundWaveData_87385E4:: @ 87385E4
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_873A594:: @ 873A594
	.incbin "sound/direct_sound_samples/873A594.bin"

	.align 2
DirectSoundWaveData_873D874:: @ 873D874
	.incbin "sound/direct_sound_samples/873D874.bin"

	.align 2
DirectSoundWaveData_873E2A4:: @ 873E2A4
	.incbin "sound/direct_sound_samples/873E2A4.bin"

	.align 2
DirectSoundWaveData_873ECD8:: @ 873ECD8
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818:: @ 8740818
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_87410E0:: @ 87410E0
	.incbin "sound/direct_sound_samples/87410E0.bin"

	.align 2
DirectSoundWaveData_87424B0:: @ 87424B0
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0:: @ 87430C0
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50:: @ 8743C50
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC:: @ 87446EC
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034:: @ 8745034
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C:: @ 8745A7C
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
DirectSoundWaveData_88D4A18:: @ 88D4A18
	.incbin "sound/direct_sound_samples/88D4A18.bin"

	.align 2
DirectSoundWaveData_88D6978:: @ 88D6978
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_88D8418:: @ 88D8418
	.incbin "sound/direct_sound_samples/88D8418.bin"

	.align 2
DirectSoundWaveData_88DA388:: @ 88DA388
	.incbin "sound/direct_sound_samples/88DA388.bin"

	.align 2
DirectSoundWaveData_88DBBC0:: @ 88DBBC0
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220:: @ 88DC220
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704:: @ 88DC704
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054:: @ 88DD054
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4:: @ 88DDAC4
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4:: @ 88DDDE4
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C:: @ 88DEA6C
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C:: @ 88DF08C
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414:: @ 88DF414
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8:: @ 88E01F8
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68:: @ 88E0B68
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04:: @ 88E0F04
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8:: @ 88E16B8
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414:: @ 88E2414
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658:: @ 88E2658
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498:: @ 88E3498
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC:: @ 88E3DEC
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140:: @ 88E4140
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774:: @ 88E4774
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0:: @ 88E53E0
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978:: @ 88E5978
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C:: @ 88E647C
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80:: @ 88E6A80
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78:: @ 88E6C78
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC:: @ 88E75DC
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568:: @ 88E8568
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0:: @ 88E8BA0
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674:: @ 88E9674
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8:: @ 88EA5B8
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30:: @ 88EAB30
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C:: @ 88EB97C
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884:: @ 88EC884
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358:: @ 88ED358
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC:: @ 88EDEEC
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4:: @ 88EE8C4
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04:: @ 88EEF04
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4:: @ 88EF9E4
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020:: @ 88F0020
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738:: @ 88F0738
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074:: @ 88F1074
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830:: @ 88F1830
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94:: @ 88F1D94
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08:: @ 88F2B08
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84:: @ 88F2F84
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470:: @ 88F3470
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38:: @ 88F3C38
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834:: @ 88F4834
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC:: @ 88F4BAC
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368:: @ 88F5368
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC:: @ 88F5FCC
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498:: @ 88F6498
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_88F6F48:: @ 88F6F48
	.incbin "sound/direct_sound_samples/88F6F48.bin"

	.align 2
DirectSoundWaveData_88F8318:: @ 88F8318
	.incbin "sound/direct_sound_samples/88F8318.bin"

	.align 2
DirectSoundWaveData_88F94DC:: @ 88F94DC
	.incbin "sound/direct_sound_samples/88F94DC.bin"

	.align 2
DirectSoundWaveData_88F9F3C:: @ 88F9F3C
	.incbin "sound/direct_sound_samples/88F9F3C.bin"
