	.align 2
DirectSoundWaveData_8456330:: @ 8456330
	.incbin "sound/direct_sound_samples/8456330.bin"

	.align 2
DirectSoundWaveData_84569D4:: @ 84569D4
	.incbin "sound/direct_sound_samples/84569D4.bin"

	.align 2
DirectSoundWaveData_84571CC:: @ 84571CC
	.incbin "sound/direct_sound_samples/84571CC.bin"

	.align 2
DirectSoundWaveData_8457D98:: @ 8457D98
	.incbin "sound/direct_sound_samples/8457D98.bin"

	.align 2
DirectSoundWaveData_8458CD0:: @ 8458CD0
	.incbin "sound/direct_sound_samples/8458CD0.bin"

	.align 2
DirectSoundWaveData_8459944:: @ 8459944
	.incbin "sound/direct_sound_samples/8459944.bin"

	.align 2
DirectSoundWaveData_845AE14:: @ 845AE14
	.incbin "sound/direct_sound_samples/845AE14.bin"

	.align 2
DirectSoundWaveData_845B2B4:: @ 845B2B4
	.incbin "sound/direct_sound_samples/845B2B4.bin"

	.align 2
DirectSoundWaveData_845B9A8:: @ 845B9A8
	.incbin "sound/direct_sound_samples/845B9A8.bin"

	.align 2
DirectSoundWaveData_845C238:: @ 845C238
	.incbin "sound/direct_sound_samples/845C238.bin"

	.align 2
DirectSoundWaveData_845CAB0:: @ 845CAB0
	.incbin "sound/direct_sound_samples/845CAB0.bin"

	.align 2
DirectSoundWaveData_845DAF0:: @ 845DAF0
	.incbin "sound/direct_sound_samples/845DAF0.bin"

	.align 2
DirectSoundWaveData_845DF04:: @ 845DF04
	.incbin "sound/direct_sound_samples/845DF04.bin"

	.align 2
DirectSoundWaveData_845ED34:: @ 845ED34
	.incbin "sound/direct_sound_samples/845ED34.bin"

	.align 2
DirectSoundWaveData_845FCC8:: @ 845FCC8
	.incbin "sound/direct_sound_samples/845FCC8.bin"

	.align 2
DirectSoundWaveData_846057C:: @ 846057C
	.incbin "sound/direct_sound_samples/846057C.bin"

	.align 2
DirectSoundWaveData_8460E60:: @ 8460E60
	.incbin "sound/direct_sound_samples/8460E60.bin"

	.align 2
DirectSoundWaveData_8461D8C:: @ 8461D8C
	.incbin "sound/direct_sound_samples/8461D8C.bin"

	.align 2
DirectSoundWaveData_84622A4:: @ 84622A4
	.incbin "sound/direct_sound_samples/84622A4.bin"

	.align 2
DirectSoundWaveData_846286C:: @ 846286C
	.incbin "sound/direct_sound_samples/846286C.bin"

	.align 2
DirectSoundWaveData_84637CC:: @ 84637CC
	.incbin "sound/direct_sound_samples/84637CC.bin"

	.align 2
DirectSoundWaveData_8464E2C:: @ 8464E2C
	.incbin "sound/direct_sound_samples/8464E2C.bin"

	.align 2
DirectSoundWaveData_8466388:: @ 8466388
	.incbin "sound/direct_sound_samples/8466388.bin"

	.align 2
DirectSoundWaveData_8466F14:: @ 8466F14
	.incbin "sound/direct_sound_samples/8466F14.bin"

	.align 2
DirectSoundWaveData_846A4B8:: @ 846A4B8
	.incbin "sound/direct_sound_samples/846A4B8.bin"

	.align 2
DirectSoundWaveData_846C7D4:: @ 846C7D4
	.incbin "sound/direct_sound_samples/846C7D4.bin"

	.align 2
DirectSoundWaveData_846FEA0:: @ 846FEA0
	.incbin "sound/direct_sound_samples/846FEA0.bin"

	.align 2
DirectSoundWaveData_84711F0:: @ 84711F0
	.incbin "sound/direct_sound_samples/84711F0.bin"

	.align 2
DirectSoundWaveData_8472700:: @ 8472700
	.incbin "sound/direct_sound_samples/8472700.bin"

	.align 2
DirectSoundWaveData_8473B20:: @ 8473B20
	.incbin "sound/direct_sound_samples/8473B20.bin"

	.align 2
DirectSoundWaveData_8474BBC:: @ 8474BBC
	.incbin "sound/direct_sound_samples/8474BBC.bin"

	.align 2
DirectSoundWaveData_8475C18:: @ 8475C18
	.incbin "sound/direct_sound_samples/8475C18.bin"

	.align 2
DirectSoundWaveData_847CBAC:: @ 847CBAC
	.incbin "sound/direct_sound_samples/847CBAC.bin"

	.align 2
DirectSoundWaveData_8481130:: @ 8481130
	.incbin "sound/direct_sound_samples/8481130.bin"

	.align 2
DirectSoundWaveData_84830A0:: @ 84830A0
	.incbin "sound/direct_sound_samples/84830A0.bin"

	.align 2
DirectSoundWaveData_8483804:: @ 8483804
	.incbin "sound/direct_sound_samples/8483804.bin"

	.align 2
DirectSoundWaveData_8485454:: @ 8485454
	.incbin "sound/direct_sound_samples/8485454.bin"

	.align 2
DirectSoundWaveData_8486924:: @ 8486924
	.incbin "sound/direct_sound_samples/8486924.bin"

	.align 2
DirectSoundWaveData_8487330:: @ 8487330
	.incbin "sound/direct_sound_samples/8487330.bin"

	.align 2
DirectSoundWaveData_8488F44:: @ 8488F44
	.incbin "sound/direct_sound_samples/8488F44.bin"

	.align 2
DirectSoundWaveData_848A8A4:: @ 848A8A4
	.incbin "sound/direct_sound_samples/848A8A4.bin"

	.align 2
DirectSoundWaveData_848BD68:: @ 848BD68
	.incbin "sound/direct_sound_samples/848BD68.bin"

	.align 2
DirectSoundWaveData_848C4A4:: @ 848C4A4
	.incbin "sound/direct_sound_samples/848C4A4.bin"

	.align 2
DirectSoundWaveData_848E094:: @ 848E094
	.incbin "sound/direct_sound_samples/848E094.bin"

	.align 2
DirectSoundWaveData_848F448:: @ 848F448
	.incbin "sound/direct_sound_samples/848F448.bin"

	.align 2
DirectSoundWaveData_8491ACC:: @ 8491ACC
	.incbin "sound/direct_sound_samples/8491ACC.bin"

	.align 2
DirectSoundWaveData_8492D10:: @ 8492D10
	.incbin "sound/direct_sound_samples/8492D10.bin"

	.align 2
DirectSoundWaveData_8493D20:: @ 8493D20
	.incbin "sound/direct_sound_samples/8493D20.bin"

	.align 2
DirectSoundWaveData_8495028:: @ 8495028
	.incbin "sound/direct_sound_samples/8495028.bin"

	.align 2
DirectSoundWaveData_8497134:: @ 8497134
	.incbin "sound/direct_sound_samples/8497134.bin"

	.align 2
DirectSoundWaveData_8499110:: @ 8499110
	.incbin "sound/direct_sound_samples/8499110.bin"

	.align 2
DirectSoundWaveData_849B320:: @ 849B320
	.incbin "sound/direct_sound_samples/849B320.bin"

	.align 2
DirectSoundWaveData_849BAEC:: @ 849BAEC
	.incbin "sound/direct_sound_samples/849BAEC.bin"

	.align 2
DirectSoundWaveData_849D45C:: @ 849D45C
	.incbin "sound/direct_sound_samples/849D45C.bin"

	.align 2
DirectSoundWaveData_849F40C:: @ 849F40C
	.incbin "sound/direct_sound_samples/849F40C.bin"

	.align 2
DirectSoundWaveData_84A26EC:: @ 84A26EC
	.incbin "sound/direct_sound_samples/84A26EC.bin"

	.align 2
DirectSoundWaveData_84A311C:: @ 84A311C
	.incbin "sound/direct_sound_samples/84A311C.bin"

	.align 2
DirectSoundWaveData_84A3B50:: @ 84A3B50
	.incbin "sound/direct_sound_samples/84A3B50.bin"

	.align 2
DirectSoundWaveData_84A5690:: @ 84A5690
	.incbin "sound/direct_sound_samples/84A5690.bin"

	.align 2
DirectSoundWaveData_84A5F58:: @ 84A5F58
	.incbin "sound/direct_sound_samples/84A5F58.bin"

	.align 2
DirectSoundWaveData_84A7328:: @ 84A7328
	.incbin "sound/direct_sound_samples/84A7328.bin"

	.align 2
DirectSoundWaveData_84A7F38:: @ 84A7F38
	.incbin "sound/direct_sound_samples/84A7F38.bin"

	.align 2
DirectSoundWaveData_84A8AC8:: @ 84A8AC8
	.incbin "sound/direct_sound_samples/84A8AC8.bin"

	.align 2
DirectSoundWaveData_84A9564:: @ 84A9564
	.incbin "sound/direct_sound_samples/84A9564.bin"

	.align 2
DirectSoundWaveData_84A9EAC:: @ 84A9EAC
	.incbin "sound/direct_sound_samples/84A9EAC.bin"

	.align 2
DirectSoundWaveData_84AA8F4:: @ 84AA8F4
	.incbin "sound/direct_sound_samples/84AA8F4.bin"

	.align 2
DirectSoundWaveData_8639898:: @ 8639898
	.incbin "sound/direct_sound_samples/8639898.bin"

	.align 2
DirectSoundWaveData_8639EF8:: @ 8639EF8
	.incbin "sound/direct_sound_samples/8639EF8.bin"

	.align 2
DirectSoundWaveData_863A3DC:: @ 863A3DC
	.incbin "sound/direct_sound_samples/863A3DC.bin"

	.align 2
DirectSoundWaveData_863AD2C:: @ 863AD2C
	.incbin "sound/direct_sound_samples/863AD2C.bin"

	.align 2
DirectSoundWaveData_863B79C:: @ 863B79C
	.incbin "sound/direct_sound_samples/863B79C.bin"

	.align 2
DirectSoundWaveData_863BABC:: @ 863BABC
	.incbin "sound/direct_sound_samples/863BABC.bin"

	.align 2
DirectSoundWaveData_863C744:: @ 863C744
	.incbin "sound/direct_sound_samples/863C744.bin"

	.align 2
DirectSoundWaveData_863CD64:: @ 863CD64
	.incbin "sound/direct_sound_samples/863CD64.bin"

	.align 2
DirectSoundWaveData_863D0EC:: @ 863D0EC
	.incbin "sound/direct_sound_samples/863D0EC.bin"

	.align 2
DirectSoundWaveData_863DED0:: @ 863DED0
	.incbin "sound/direct_sound_samples/863DED0.bin"

	.align 2
DirectSoundWaveData_863E840:: @ 863E840
	.incbin "sound/direct_sound_samples/863E840.bin"

	.align 2
DirectSoundWaveData_863EBDC:: @ 863EBDC
	.incbin "sound/direct_sound_samples/863EBDC.bin"

	.align 2
DirectSoundWaveData_863F390:: @ 863F390
	.incbin "sound/direct_sound_samples/863F390.bin"

	.align 2
DirectSoundWaveData_86400EC:: @ 86400EC
	.incbin "sound/direct_sound_samples/86400EC.bin"

	.align 2
DirectSoundWaveData_8640330:: @ 8640330
	.incbin "sound/direct_sound_samples/8640330.bin"

	.align 2
DirectSoundWaveData_8641170:: @ 8641170
	.incbin "sound/direct_sound_samples/8641170.bin"

	.align 2
DirectSoundWaveData_8641AC4:: @ 8641AC4
	.incbin "sound/direct_sound_samples/8641AC4.bin"

	.align 2
DirectSoundWaveData_8641E18:: @ 8641E18
	.incbin "sound/direct_sound_samples/8641E18.bin"

	.align 2
DirectSoundWaveData_864244C:: @ 864244C
	.incbin "sound/direct_sound_samples/864244C.bin"

	.align 2
DirectSoundWaveData_86430B8:: @ 86430B8
	.incbin "sound/direct_sound_samples/86430B8.bin"

	.align 2
DirectSoundWaveData_8643650:: @ 8643650
	.incbin "sound/direct_sound_samples/8643650.bin"

	.align 2
DirectSoundWaveData_8644154:: @ 8644154
	.incbin "sound/direct_sound_samples/8644154.bin"

	.align 2
DirectSoundWaveData_8644758:: @ 8644758
	.incbin "sound/direct_sound_samples/8644758.bin"

	.align 2
DirectSoundWaveData_8644950:: @ 8644950
	.incbin "sound/direct_sound_samples/8644950.bin"

	.align 2
DirectSoundWaveData_86452B4:: @ 86452B4
	.incbin "sound/direct_sound_samples/86452B4.bin"

	.align 2
DirectSoundWaveData_8646240:: @ 8646240
	.incbin "sound/direct_sound_samples/8646240.bin"

	.align 2
DirectSoundWaveData_8646878:: @ 8646878
	.incbin "sound/direct_sound_samples/8646878.bin"

	.align 2
DirectSoundWaveData_864734C:: @ 864734C
	.incbin "sound/direct_sound_samples/864734C.bin"

	.align 2
DirectSoundWaveData_8648290:: @ 8648290
	.incbin "sound/direct_sound_samples/8648290.bin"

	.align 2
DirectSoundWaveData_8648808:: @ 8648808
	.incbin "sound/direct_sound_samples/8648808.bin"

	.align 2
DirectSoundWaveData_8649654:: @ 8649654
	.incbin "sound/direct_sound_samples/8649654.bin"

	.align 2
DirectSoundWaveData_864A55C:: @ 864A55C
	.incbin "sound/direct_sound_samples/864A55C.bin"

	.align 2
DirectSoundWaveData_864B030:: @ 864B030
	.incbin "sound/direct_sound_samples/864B030.bin"

	.align 2
DirectSoundWaveData_864BBC4:: @ 864BBC4
	.incbin "sound/direct_sound_samples/864BBC4.bin"

	.align 2
DirectSoundWaveData_864C59C:: @ 864C59C
	.incbin "sound/direct_sound_samples/864C59C.bin"

	.align 2
DirectSoundWaveData_864CBDC:: @ 864CBDC
	.incbin "sound/direct_sound_samples/864CBDC.bin"

	.align 2
DirectSoundWaveData_864D6BC:: @ 864D6BC
	.incbin "sound/direct_sound_samples/864D6BC.bin"

	.align 2
DirectSoundWaveData_864DCF8:: @ 864DCF8
	.incbin "sound/direct_sound_samples/864DCF8.bin"

	.align 2
DirectSoundWaveData_864E410:: @ 864E410
	.incbin "sound/direct_sound_samples/864E410.bin"

	.align 2
DirectSoundWaveData_864ED4C:: @ 864ED4C
	.incbin "sound/direct_sound_samples/864ED4C.bin"

	.align 2
DirectSoundWaveData_864F508:: @ 864F508
	.incbin "sound/direct_sound_samples/864F508.bin"

	.align 2
DirectSoundWaveData_864FA6C:: @ 864FA6C
	.incbin "sound/direct_sound_samples/864FA6C.bin"

	.align 2
DirectSoundWaveData_86507E0:: @ 86507E0
	.incbin "sound/direct_sound_samples/86507E0.bin"

	.align 2
DirectSoundWaveData_8650C5C:: @ 8650C5C
	.incbin "sound/direct_sound_samples/8650C5C.bin"

	.align 2
DirectSoundWaveData_8651148:: @ 8651148
	.incbin "sound/direct_sound_samples/8651148.bin"

	.align 2
DirectSoundWaveData_8651910:: @ 8651910
	.incbin "sound/direct_sound_samples/8651910.bin"

	.align 2
DirectSoundWaveData_865250C:: @ 865250C
	.incbin "sound/direct_sound_samples/865250C.bin"

	.align 2
DirectSoundWaveData_8652884:: @ 8652884
	.incbin "sound/direct_sound_samples/8652884.bin"

	.align 2
DirectSoundWaveData_8653040:: @ 8653040
	.incbin "sound/direct_sound_samples/8653040.bin"

	.align 2
DirectSoundWaveData_8653CA4:: @ 8653CA4
	.incbin "sound/direct_sound_samples/8653CA4.bin"

	.align 2
DirectSoundWaveData_8654170:: @ 8654170
	.incbin "sound/direct_sound_samples/8654170.bin"

	.align 2
DirectSoundWaveData_8654C20:: @ 8654C20
	.incbin "sound/direct_sound_samples/8654C20.bin"
