	.align 2
gSongTable:: @ 845548C
	song mus_dummy, 0, 0
	song se_use_item, 1, 1
	song se_pc_login, 1, 1
	song se_pc_off, 1, 1
	song se_pc_on, 1, 1
	song se_select, 2, 2
	song se_win_open, 1, 1
	song se_wall_hit, 2, 2
	song se_door, 1, 1
	song se_exit, 1, 1
	song se_ledge, 1, 1
	song se_bike_bell, 1, 1
	song se_not_effective, 1, 1
	song se_effective, 1, 1
	song se_super_effective, 1, 1
	song se_ball_open, 1, 1
	song se_faint, 1, 1
	song se_flee, 1, 1
	song se_sliding_door, 1, 1
	song se_ship, 1, 1
	song se_bang, 1, 1
	song se_pin, 1, 1
	song se_boo, 1, 1
	song se_ball, 1, 1
	song se_contest_place, 2, 2
	song se_a, 1, 1
	song se_i, 1, 1
	song se_u, 1, 1
	song se_e, 1, 1
	song se_o, 1, 1
	song se_n, 1, 1
	song se_success, 1, 1
	song se_failure, 1, 1
	song se_exp, 1, 1
	song se_bike_hop, 1, 1
	song se_switch, 1, 1
	song se_click, 1, 1
	song se_fu_zaku, 1, 1
	song se_contest_condition_lose, 1, 1
	song se_lavaridge_fall_warp, 1, 1
	song se_ice_stairs, 1, 1
	song se_ice_break, 1, 1
	song se_ice_crack, 1, 1
	song se_fall, 1, 1
	song se_unlock, 2, 2
	song se_warp_in, 1, 1
	song se_warp_out, 1, 1
	song se_repel, 1, 1
	song se_rotating_gate, 1, 1
	song se_truck_move, 1, 1
	song se_truck_stop, 1, 1
	song se_truck_unload, 2, 2
	song se_truck_door, 1, 1
	song se_berry_blender, 2, 2
	song se_card, 1, 1
	song se_save, 1, 1
	song se_ball_bounce_1, 1, 1
	song se_ball_bounce_2, 1, 1
	song se_ball_bounce_3, 1, 1
	song se_ball_bounce_4, 1, 1
	song se_ball_trade, 2, 2
	song se_ball_throw, 1, 1
	song se_note_c, 2, 2
	song se_note_d, 2, 2
	song se_note_e, 2, 2
	song se_note_f, 2, 2
	song se_note_g, 2, 2
	song se_note_a, 2, 2
	song se_note_b, 2, 2
	song se_note_c_high, 2, 2
	song se_puddle, 2, 2
	song se_bridge_walk, 2, 2
	song se_itemfinder, 1, 1
	song se_ding_dong, 1, 1
	song se_balloon_red, 2, 2
	song se_balloon_blue, 2, 2
	song se_balloon_yellow, 2, 2
	song se_breakable_door, 2, 2
	song se_mud_ball, 2, 2
	song se_field_poison, 1, 1
	song se_escalator, 1, 1
	song se_thunderstorm, 3, 3
	song se_thunderstorm_stop, 3, 3
	song se_downpour, 3, 3
	song se_downpour_stop, 3, 3
	song se_rain, 3, 3
	song se_rain_stop, 3, 3
	song se_thunder, 1, 1
	song se_thunder2, 1, 1
	song se_elevator, 1, 1
	song se_low_health, 3, 3
	song se_exp_max, 1, 1
	song se_roulette_ball, 2, 2
	song se_roulette_ball2, 2, 2
	song se_taillow_wing_flap, 1, 1
	song se_shop, 1, 1
	song se_contest_heart, 1, 1
	song se_contest_curtain_rise, 1, 1
	song se_contest_curtain_fall, 1, 1
	song se_contest_icon_change, 1, 1
	song se_contest_icon_clear, 1, 1
	song se_contest_mons_turn, 1, 1
	song se_shiny, 1, 1
	song se_intro_blast, 1, 1
	song se_mugshot, 1, 1
	song se_applause, 1, 1
	song se_vend, 1, 1
	song se_orb, 1, 1
	song se_dex_scroll, 1, 1
	song se_dex_page, 1, 1
	song se_pokenav_on, 1, 1
	song se_pokenav_off, 1, 1
	song se_dex_search, 1, 1
	song se_egg_hatch, 1, 1
	song se_ball_tray_enter, 1, 1
	song se_ball_tray_ball, 1, 1
	song se_ball_tray_exit, 2, 2
	song se_glass_flute, 1, 1
	song se_m_thunderbolt, 2, 2
	song se_m_thunderbolt2, 1, 1
	song se_m_harden, 1, 1
	song se_m_nightmare, 1, 1
	song se_m_vital_throw, 1, 1
	song se_m_vital_throw2, 1, 1
	song se_m_bubble, 1, 1
	song se_m_bubble2, 1, 1
	song se_m_bubble3, 1, 1
	song se_m_rain_dance, 1, 1
	song se_m_cut, 1, 1
	song se_m_string_shot, 1, 1
	song se_m_string_shot2, 1, 1
	song se_m_rock_throw, 1, 1
	song se_m_gust, 2, 2
	song se_m_gust2, 2, 2
	song se_m_double_slap, 1, 1
	song se_m_double_team, 1, 1
	song se_m_razor_wind, 1, 1
	song se_m_icy_wind, 1, 1
	song se_m_thunder_wave, 1, 1
	song se_m_comet_punch, 1, 1
	song se_m_mega_kick, 1, 1
	song se_m_mega_kick2, 1, 1
	song se_m_crabhammer, 1, 1
	song se_m_jump_kick, 1, 1
	song se_m_flame_wheel, 1, 1
	song se_m_flame_wheel2, 1, 1
	song se_m_flamethrower, 1, 1
	song se_m_fire_punch, 1, 1
	song se_m_toxic, 1, 1
	song se_m_sacred_fire, 1, 1
	song se_m_sacred_fire2, 2, 2
	song se_m_ember, 1, 1
	song se_m_take_down, 2, 2
	song se_m_blizzard, 1, 1
	song se_m_blizzard2, 1, 1
	song se_m_scratch, 1, 1
	song se_m_vicegrip, 1, 1
	song se_m_wing_attack, 1, 1
	song se_m_fly, 1, 1
	song se_m_sand_attack, 1, 1
	song se_m_razor_wind2, 1, 1
	song se_m_bite, 1, 1
	song se_m_headbutt, 1, 1
	song se_m_surf, 1, 1
	song se_m_hydro_pump, 1, 1
	song se_m_whirlpool, 1, 1
	song se_m_horn_attack, 1, 1
	song se_m_tail_whip, 2, 2
	song se_m_mist, 1, 1
	song se_m_poison_powder, 1, 1
	song se_m_bind, 2, 2
	song se_m_dragon_rage, 1, 1
	song se_m_sing, 1, 1
	song se_m_perish_song, 1, 1
	song se_m_pay_day, 1, 1
	song se_m_dig, 1, 1
	song se_m_dizzy_punch, 1, 1
	song se_m_self_destruct, 1, 1
	song se_m_explosion, 1, 1
	song se_m_absorb_2, 1, 1
	song se_m_absorb, 1, 1
	song se_m_screech, 1, 1
	song se_m_bubble_beam, 1, 1
	song se_m_bubble_beam2, 1, 1
	song se_m_supersonic, 1, 1
	song se_m_belly_drum, 1, 1
	song se_m_metronome, 1, 1
	song se_m_bonemerang, 1, 1
	song se_m_lick, 1, 1
	song se_m_psybeam, 1, 1
	song se_m_faint_attack, 1, 1
	song se_m_swords_dance, 1, 1
	song se_m_leer, 1, 1
	song se_m_swagger, 1, 1
	song se_m_swagger2, 1, 1
	song se_m_heal_bell, 1, 1
	song se_m_confuse_ray, 1, 1
	song se_m_snore, 1, 1
	song se_m_brick_break, 1, 1
	song se_m_giga_drain, 1, 1
	song se_m_psybeam2, 1, 1
	song se_m_solar_beam, 2, 2
	song se_m_petal_dance, 1, 1
	song se_m_teleport, 1, 1
	song se_m_minimize, 1, 1
	song se_m_sketch, 1, 1
	song se_m_swift, 1, 1
	song se_m_reflect, 1, 1
	song se_m_barrier, 1, 1
	song se_m_detect, 2, 2
	song se_m_lock_on, 1, 1
	song se_m_moonlight, 1, 1
	song se_m_charm, 1, 1
	song se_m_charge, 1, 1
	song se_m_strength, 1, 1
	song se_m_hyper_beam, 1, 1
	song se_m_waterfall, 1, 1
	song se_m_reversal, 1, 1
	song se_m_acid_armor, 1, 1
	song se_m_sandstorm, 1, 1
	song se_m_tri_attack, 1, 1
	song se_m_tri_attack2, 1, 1
	song se_m_encore, 1, 1
	song se_m_encore2, 2, 2
	song se_m_baton_pass, 1, 1
	song se_m_milk_drink, 1, 1
	song se_m_attract, 1, 1
	song se_m_attract2, 1, 1
	song se_m_morning_sun, 1, 1
	song se_m_flatter, 1, 1
	song se_m_sand_tomb, 1, 1
	song se_m_grasswhistle, 1, 1
	song se_m_spit_up, 1, 1
	song se_m_dive, 1, 1
	song se_m_earthquake, 2, 2
	song se_m_twister, 2, 2
	song se_m_sweet_scent, 1, 1
	song se_m_yawn, 1, 1
	song se_m_sky_uppercut, 2, 2
	song se_m_stat_increase, 1, 1
	song se_m_heat_wave, 1, 1
	song se_m_uproar, 1, 1
	song se_m_hail, 1, 1
	song se_m_cosmic_power, 2, 2
	song se_m_teeter_dance, 1, 1
	song se_m_stat_decrease, 1, 1
	song se_m_haze, 1, 1
	song se_m_hyper_beam2, 1, 1
	@ FRLG SFX below
	song se_rg_w_door, 1, 1         @ Door
	song se_rg_card1, 1, 1          @ Trainer Card 1
	song se_rg_card2, 1, 1          @ Trainer Card 2
	song se_rg_card3, 1, 1          @ Trainer Card 3
	song se_rg_bag1, 1, 1           @ Bag Scroll
	song se_rg_bag2, 1, 1           @ Bag Pocket Change
	song se_rg_getting, 1, 1        
	song se_rg_shop, 1, 1           @ Cash Register
	song se_rg_kiteki, 1, 1         @ S.S. Anne Horn
	song se_rg_help_op, 1, 1        @ Help Menu Open
	song se_rg_help_cl, 1, 1        @ Help Menu Close
	song se_rg_help_ng, 1, 1        @ Help Menu Error
	song se_rg_deomov, 1, 1         @ Deoxys Moves
	song se_rg_excellent, 1, 1
	song se_rg_nawamiss, 1, 1
	@ end FRLG SFX
	song se_toreeye, 1, 1           @ Trainer's Eye Call
	song se_toreoff, 1, 1           @ Trainer's Eye Hang Up
	song se_hantei1, 1, 1           @ Battle Arena Time's Up 1
	song se_hantei2, 1, 1           @ Battle Arena Time's Up 2
	song se_curtain, 1, 1           @ Battle Pike Curtain Open
	song se_curtain1, 1, 1          @ Battle Pike Curtain Close
	song se_ussoki, 1, 1            @ Sudowoodo
	@ end Emerald SFX
	song song_270, 2, 2
	song song_271, 2, 2
	song song_272, 2, 2
	song song_273, 2, 2
	song song_274, 2, 2
	song song_275, 2, 2
	song song_276, 2, 2
	song song_277, 2, 2
	song song_278, 2, 2
	song song_279, 2, 2
	song song_280, 2, 2
	song song_281, 2, 2
	song song_282, 2, 2
	song song_283, 2, 2
	song song_284, 2, 2
	song song_285, 2, 2
	song song_286, 2, 2
	song song_287, 2, 2
	song song_288, 2, 2
	song song_289, 2, 2
	song song_290, 2, 2
	song song_291, 2, 2
	song song_292, 2, 2
	song song_293, 2, 2
	song song_294, 2, 2
	song song_295, 2, 2
	song song_296, 2, 2
	song song_297, 2, 2
	song song_298, 2, 2
	song mus_littleroot_test, 0, 0
	song mus_gsc_route38, 0, 0
	song mus_caught, 0, 0
	song mus_victory_wild, 0, 0
	song mus_victory_gym_leader, 0, 0
	song mus_victory_league, 0, 0
	song mus_c_comm_center, 0, 0
	song mus_gsc_pewter, 0, 0
	song mus_c_vs_legend_beast, 0, 0
	song mus_route101, 0, 0
	song mus_route110, 0, 0
	song mus_route120, 0, 0
	song mus_petalburg, 0, 0
	song mus_oldale, 0, 0
	song mus_gym, 0, 0
	song mus_surf, 0, 0
	song mus_petalburg_woods, 0, 0
	song mus_level_up, 2, 2
	song mus_heal, 2, 2
	song mus_obtain_badge, 2, 2
	song mus_obtain_item, 2, 2
	song mus_evolved, 2, 2
	song mus_obtain_tmhm, 2, 2
	song mus_lilycove_museum, 0, 0
	song mus_route122, 0, 0
	song mus_oceanic_museum, 0, 0
	song mus_evolution_intro, 2, 2
	song mus_evolution, 0, 0
	song mus_move_deleted, 2, 2
	song mus_encounter_girl, 0, 0
	song mus_encounter_male, 0, 0
	song mus_abandoned_ship, 0, 0
	song mus_fortree, 0, 0
	song mus_birch_lab, 0, 0
	song mus_b_tower, 0, 0
	song mus_encounter_swimmer, 0, 0
	song mus_cave_of_origin, 0, 0
	song mus_obtain_berry, 2, 2
	song mus_awaken_legend, 2, 2
	song mus_slots_jackpot, 2, 2
	song mus_slots_win, 2, 2
	song mus_too_bad, 2, 2
	song mus_roulette, 0, 0
	song mus_link_contest_p1, 0, 0
	song mus_link_contest_p2, 0, 0
	song mus_link_contest_p3, 0, 0
	song mus_link_contest_p4, 0, 0
	song mus_encounter_rich, 0, 0
	song mus_verdanturf, 0, 0
	song mus_rustboro, 0, 0
	song mus_poke_center, 0, 0
	song mus_route104, 0, 0
	song mus_route119, 0, 0
	song mus_cycling, 0, 0
	song mus_poke_mart, 0, 0
	song mus_littleroot, 0, 0
	song mus_mt_chimney, 0, 0
	song mus_encounter_female, 0, 0
	song mus_lilycove, 0, 0
	song mus_route111, 0, 0
	song mus_help, 0, 0
	song mus_underwater, 0, 0
	song mus_victory_trainer, 0, 0
	song mus_title, 0, 0
	song mus_intro, 0, 0
	song mus_encounter_may, 0, 0
	song mus_encounter_intense, 0, 0
	song mus_encounter_cool, 0, 0
	song mus_route113, 0, 0
	song mus_encounter_aqua, 0, 0
	song mus_follow_me, 0, 0
	song mus_encounter_brendan, 0, 0
	song mus_ever_grande, 0, 0
	song mus_encounter_suspicious, 0, 0
	song mus_victory_aqua_magma, 0, 0
	song mus_cable_car, 0, 0
	song mus_game_corner, 0, 0
	song mus_dewford, 0, 0
	song mus_safari_zone, 0, 0
	song mus_victory_road, 0, 0
	song mus_aqua_magma_hideout, 0, 0
	song mus_sailing, 0, 0
	song mus_mt_pyre, 0, 0
	song mus_slateport, 0, 0
	song mus_mt_pyre_exterior, 0, 0
	song mus_school, 0, 0
	song mus_hall_of_fame, 0, 0
	song mus_fallarbor, 0, 0
	song mus_sealed_chamber, 0, 0
	song mus_contest_winner, 0, 0
	song mus_contest, 0, 0
	song mus_encounter_magma, 0, 0
	song mus_intro_battle, 0, 0
	song mus_weather_kyogre, 0, 0
	song mus_weather_groudon, 0, 0
	song mus_sootopolis, 0, 0
	song mus_contest_results, 0, 0
	song mus_hall_of_fame_room, 0, 0
	song mus_trick_house, 0, 0
	song mus_encounter_twins, 0, 0
	song mus_encounter_elite_four, 0, 0
	song mus_encounter_hiker, 0, 0
	song mus_contest_lobby, 0, 0
	song mus_encounter_interviewer, 0, 0
	song mus_encounter_champion, 0, 0
	song mus_credits, 0, 0
	song mus_end, 0, 0
	song mus_vs_wild, 0, 0
	song mus_vs_aqua_magma, 0, 0
	song mus_vs_trainer, 0, 0
	song mus_vs_gym_leader, 0, 0
	song mus_vs_champion, 0, 0
	song mus_vs_regi, 0, 0
	song mus_vs_kyogre_groudon, 0, 0
	song mus_vs_rival, 0, 0
	song mus_vs_elite_four, 0, 0
	song mus_vs_aqua_magma_leader, 0, 0
	song mus_radio_tower_takeover, 0, 0
	song mus_ooame, 0, 0            @ The Flood (Emerald)
	song mus_b_frontier, 0, 0       @ Battle Frontier
	song mus_b_arena, 0, 0          @ Battle Arena
	song mus_me_pointget, 2, 2      @ Obtained Battle Points!
	song mus_me_tore_eye, 2, 2      @ Registered Trainer!
	song mus_pyramid, 0, 0          @ Battle Pyramid
	song mus_pyramid_top, 0, 0      @ Top of the Battle Pyramid
	song mus_b_palace, 0, 0         @ Battle Palace
	song mus_rekkuu_kourin, 0, 0    @ Rayquaza Enters
	song mus_sattower, 0, 0         @ Battle Tower (Emerald)
	song mus_me_symbolget, 2, 2     @ Obtained a Frontier Symbol!
	song mus_b_dome, 0, 0           @ Battle Dome
	song mus_b_tube, 0, 0           @ Battle Pike
	song mus_b_factory, 0, 0        @ Battle Factory
	song mus_vs_rekku, 0, 0         @ Battle! Legendary Pokémon
	song mus_vs_front, 0, 0         @ Battle! Frontier Brain
	song mus_vs_mew, 0, 0           @ Battle! Mew
	song mus_b_dome1, 0, 0          @ Battle Dome Lobby
	@ FRLG Music Below
	song mus_rg_annai, 0, 0         @ Follow Me!
	song mus_rg_slot, 0, 0          @ Game Corner
	song mus_rg_ajito, 0, 0         @ Rocket Hideout
	song mus_rg_gym, 0, 0           @ Gym
	song mus_rg_purin, 2, 2         @ Jigglypuff's Song
	song mus_rg_demo, 0, 0          @ Opening Movie
	song mus_rg_title, 0, 0         @ Title Screen
	song mus_rg_guren, 0, 0         @ Cinnabar Island
	song mus_rg_shion, 0, 0         @ Lavender Town
	song mus_rg_kaihuku, 0, 0       @ RBY Pokémon Center Healing
	song mus_rg_cycling, 0, 0       @ Cycling
	song mus_rg_rocket, 0, 0        @ Encounter! Team Rocket
	song mus_rg_shoujo, 0, 0        @ Encounter! Girl
	song mus_rg_shounen, 0, 0       @ Encounter! Boy
	song mus_rg_dendou, 0, 0        @ You're the Champion!
	song mus_rg_t_mori, 0, 0        @ Viridian Forest
	song mus_rg_otsukimi, 0, 0      @ Mt. Moon
	song mus_rg_pokeyashi, 0, 0     @ Pokémon Mansion
	song mus_rg_ending, 0, 0        @ Credits
	song mus_rg_load01, 0, 0        @ Route 1
	song mus_rg_opening, 0, 0       @ Route 24/Intro
	song mus_rg_load02, 0, 0        @ Route 3
	song mus_rg_load03, 0, 0        @ Route 11
	song mus_rg_champ_r, 0, 0       @ Victory Road/Indigo Plateau
	song mus_rg_vs_gym, 0, 0        @ Battle! Gym Leader/Elite Four
	song mus_rg_vs_tore, 0, 0       @ Battle! Trainer
	song mus_rg_vs_yasei, 0, 0      @ Battle! Wild Pokémon
	song mus_rg_vs_last, 0, 0       @ Battle! Champion
	song mus_rg_masara, 0, 0        @ Pallet Town
	song mus_rg_kenkyu, 0, 0        @ Professor Oak's Lab
	song mus_rg_ohkido, 0, 0        @ Professor Oak's Theme
	song mus_rg_pokecen, 0, 0       @ Pokémon Center
	song mus_rg_santoan, 0, 0       @ S.S. Anne
	song mus_rg_naminori, 0, 0      @ Surfing
	song mus_rg_p_tower, 0, 0       @ Pokémon Tower
	song mus_rg_shiruhu, 0, 0       @ Silph Co.
	song mus_rg_hanada, 0, 0        @ Cerulean/Fuschia City
	song mus_rg_tamamusi, 0, 0      @ Celadon City
	song mus_rg_win_tre, 0, 0       @ Victory! Trainer
	song mus_rg_win_yasei, 0, 0     @ Victory! Wild Pokémon
	song mus_rg_win_gym, 0, 0       @ Victory! Gym Leader
	song mus_rg_kuchiba, 0, 0       @ Vermillion City
	song mus_rg_nibi, 0, 0          @ Viridian/Saffron/Pewter City
	song mus_rg_rival1, 0, 0        @ Encounter! Rival
	song mus_rg_rival2, 0, 0        @ Rival's Exit
	song mus_rg_fan2, 2, 2          @ Fanfare 2
	song mus_rg_fan5, 2, 2          @ Obtained a Starter!
	song mus_rg_fan6, 2, 2          @ Pokémon Caught! (Used in Emerald)
	song mus_me_rg_photo, 2, 2      @ Trainer Photo
	song mus_rg_titlerog, 0, 0      @ Game Freak
	song mus_rg_get_yasei, 0, 0     @ Pokémon Caught Victory Theme
	song mus_rg_sousa, 0, 0         @ Starting Tutorial
	song mus_rg_sekaikan, 0, 0      @ Starting Tutorial 2
	song mus_rg_seibetu, 0, 0       @ Starting Tutorial 3
	song mus_rg_jump, 0, 0          @ Jumping Minigame
	song mus_rg_union, 0, 0         @ Union Room
	song mus_rg_network, 0, 0       @ Network Center
	song mus_rg_okurimono, 0, 0     @ Mystery Gift
	song mus_rg_kinomikui, 0, 0
	song mus_rg_nanadungeon, 0, 0   @ Sevii Caves/Altering Cave (Mt. Moon)
	song mus_rg_oshie_tv, 0, 0      @ Follow Me!
	song mus_rg_nanashima, 0, 0     @ Sevii Islands Routes (Lake of Rage)
	song mus_rg_nanaiseki, 0, 0     @ Sevii Forests (Viridian Forest)
	song mus_rg_nana123, 0, 0       @ Sevii Islands 1-3 (Viridian/Saffron/Pewter)
	song mus_rg_nana45, 0, 0        @ Sevii Islands 4-5 (Azalea Town)
	song mus_rg_nana67, 0, 0        @ Sevii Islands 6-7 (Violet City)
	song mus_rg_pokefue, 2, 2       @ Poké Flute
	song mus_rg_vs_deo, 0, 0        @ Battle! Deoxys
	song mus_rg_vs_myu2, 0, 0       @ Battle! Mewtwo
	song mus_rg_vs_den, 0, 0        @ Battle! Legendary Birds
	song mus_rg_exeye, 0, 0         @ Encounter! Gym Leader
	song mus_rg_deoeye, 0, 0        @ Encounter! Deoxys
	song mus_rg_t_tower, 0, 0       @ Trainer Tower (Gym)
	song mus_rg_slowmasara, 0, 0    @ Pallet Town (Hall of Fame remix)
	song mus_rg_tvnoize, 0, 0       @ Teachy TV
	song ph_trap_blend, 2, 2
	song ph_trap_held, 2, 2
	song ph_trap_solo, 2, 2
	song ph_face_blend, 2, 2
	song ph_face_held, 2, 2
	song ph_face_solo, 2, 2
	song ph_cloth_blend, 2, 2
	song ph_cloth_held, 2, 2
	song ph_cloth_solo, 2, 2
	song ph_dress_blend, 2, 2
	song ph_dress_held, 2, 2
	song ph_dress_solo, 2, 2
	song ph_fleece_blend, 2, 2
	song ph_fleece_held, 2, 2
	song ph_fleece_solo, 2, 2
	song ph_kit_blend, 2, 2
	song ph_kit_held, 2, 2
	song ph_kit_solo, 2, 2
	song ph_price_blend, 2, 2
	song ph_price_held, 2, 2
	song ph_price_solo, 2, 2
	song ph_lot_blend, 2, 2
	song ph_lot_held, 2, 2
	song ph_lot_solo, 2, 2
	song ph_goat_blend, 2, 2
	song ph_goat_held, 2, 2
	song ph_goat_solo, 2, 2
	song ph_thought_blend, 2, 2
	song ph_thought_held, 2, 2
	song ph_thought_solo, 2, 2
	song ph_choice_blend, 2, 2
	song ph_choice_held, 2, 2
	song ph_choice_solo, 2, 2
	song ph_mouth_blend, 2, 2
	song ph_mouth_held, 2, 2
	song ph_mouth_solo, 2, 2
	song ph_foot_blend, 2, 2
	song ph_foot_held, 2, 2
	song ph_foot_solo, 2, 2
	song ph_goose_blend, 2, 2
	song ph_goose_held, 2, 2
	song ph_goose_solo, 2, 2
	song ph_strut_blend, 2, 2
	song ph_strut_held, 2, 2
	song ph_strut_solo, 2, 2
	song ph_cure_blend, 2, 2
	song ph_cure_held, 2, 2
	song ph_cure_solo, 2, 2
	song ph_nurse_blend, 2, 2
	song ph_nurse_held, 2, 2
	song ph_nurse_solo, 2, 2

	.align 2
dummy_song_header: @ 86B5D00
	.byte 0, 0, 0, 0
