	.ifndef GERMAN
EverGrandeCity_Text_16A74D:: @ 816A74D
	.string "ENTERING VICTORY ROAD$"

EverGrandeCity_Text_16A763:: @ 816A763
	.string "ENTERING POKéMON LEAGUE\n"
	.string "CENTER GATE$"

EverGrandeCity_Text_16A787:: @ 816A787
	.string "EVER GRANDE CITY\p"
	.string "“The paradise of flowers, the sea,\n"
	.string "and POKéMON.”$"
	.else
EverGrandeCity_Text_16A74D:: @ 816A74D
	.string "SIE BETRETEN DIE SIEGESSTRASSE$"

EverGrandeCity_Text_16A763:: @ 816A763
	.string "SIE ERREICHEN DEN EINGANG ZUR\n"
	.string "POKéMON LIGA$"

EverGrandeCity_Text_16A787:: @ 816A787
	.string "PRACHTPOLIS CITY\p"
	.string "“Das Paradies der Blumen, des Meeres\n"
	.string "und der POKéMON.”$"
	.endif
