gAbilityNames:: @ 81FA248
	.string "-------$", 13
	.string "Stench$", 13
	.string "Drizzle$", 13
	.string "Speed Boost$", 13
	.string "Battle Armor$", 13
	.string "Sturdy$", 13
	.string "Damp$", 13
	.string "Limber$", 13
	.string "Sand Veil$", 13
	.string "Static$", 13
	.string "Volt Absorb$", 13
	.string "Water Absorb$", 13
	.string "Oblivious$", 13
	.string "Cloud Nine$", 13
	.string "Compoundeyes$", 13
	.string "Imsomnia$", 13
	.string "Color Change$", 13
	.string "Immunity$", 13
	.string "Flash Fire$", 13
	.string "Shield Dust$", 13
	.string "Own Tempo$", 13
	.string "Suction Cups$", 13
	.string "Intimidate$", 13
	.string "Shadow Tag$", 13
	.string "Rough Skin$", 13
	.string "Wonder Guard$", 13
	.string "Levitate$", 13
	.string "Effect Spore$", 13
	.string "Synchronize$", 13
	.string "Clear Body$", 13
	.string "Natural Cure$", 13
	.string "Lightningrod$", 13
	.string "Serene Grace$", 13
	.string "Swift Swim$", 13
	.string "Chlorophyil$", 13
	.string "Illuminate$", 13
	.string "Trace$", 13
	.string "Huge Power$", 13
	.string "Poison Point$", 13
	.string "Inner Focus$", 13
	.string "Magma Armor$", 13
	.string "Water Veil$", 13
	.string "Magnet Pull$", 13
	.string "Soundproof$", 13
	.string "Rain Dish$", 13
	.string "Sand Stream$", 13
	.string "Pressure$", 13
	.string "Thick Fat$", 13
	.string "Early Bird$", 13
	.string "Flame Body$", 13
	.string "Run Away$", 13
	.string "Keen Eye$", 13
	.string "Hyper Cutter$", 13
	.string "Pickup$", 13
	.string "Truant$", 13
	.string "Hustle$", 13
	.string "Cute Charm$", 13
	.string "Plus$", 13
	.string "Minus$", 13
	.string "Forecast$", 13
	.string "Sticky Hold$", 13
	.string "Shed Skin$", 13
	.string "Guts$", 13
	.string "Marvel Scale$", 13
	.string "Liquid Ooze$", 13
	.string "Overgrow$", 13
	.string "Blaze$", 13
	.string "Torrent$", 13
	.string "Swarm$", 13
	.string "Rock Head$", 13
	.string "Drought$", 13
	.string "Arena Trap$", 13
	.string "Vital Spirit$", 13
	.string "White Smoke$", 13
	.string "Pure Power$", 13
	.string "Shell Armor$", 13
	.string "Snow Warning$", 13
	.string "Air Lock$", 13
