UnknownString_81B4F03: @ 81B4F03
	.string "{PLAYER}’s Blue Orb suddenly began\n"
	.string "glowing!$"

UnknownString_81B4F29: @ 81B4F29
	.string "Kyogre appears to have settled\n"
	.string "into sleep again...$"

UnknownString_81B4F5C: @ 81B4F5C
	.string "Archie: This...$"

UnknownString_81B4F6C: @ 81B4F6C
	.string "Archie: ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "This is good-bye.\n"
	.string "This is the last you’ve seen of me...$"
