UnknownString_81B41B8: @ 81B41B8
	.string "Archie: Hold it right there.$"

UnknownString_81B41D5: @ 81B41D5
	.string "Archie: Fufufu...\n"
	.string "So it was you, after all.$"

UnknownString_81B4201: @ 81B4201
	.string "Archie: Behold!\p"
	.string "See how beautiful it is, the sleeping\n"
	.string "form of the ancient Pokémon Kyogre!\p"
	.string "I have waited so long for this day to\n"
	.string "come...$"

UnknownString_81B4289: @ 81B4289
	.string "Archie: It surprises me, how you’ve\n"
	.string "managed to chase me here.\p"
	.string "But that’s all over now.\p"
	.string "For the realization of my dream,\n"
	.string "you must disappear now!$"

UnknownString_81B4319: @ 81B4319
	.string "I...\n"
	.string "I lost again?$"

UnknownString_81B432C: @ 81B432C
	.string "Archie: Fufufu...\p"
	.string "I commend you. I must recognize that\n"
	.string "you are truly gifted.\p"
	.string "But!\n"
	.string "I have this in my possession!\p"
	.string "With this Red Orb, I can make Kyogre...$"

UnknownString_81B43C4: @ 81B43C4
	.string "The Red Orb suddenly began shining\n"
	.string "by itself!$"

UnknownString_81B43F2: @ 81B43F2
	.string "Archie: What?!\p"
	.string "I didn’t do anything.\n"
	.string "Why did the Red Orb...\p"
	.string "Where did Kyogre go?$"

UnknownString_81B4443: @ 81B4443
	.string "Archie: Hm? It’s a message from our\n"
	.string "members outside...$"

UnknownString_81B447A: @ 81B447A
	.string "Archie: Yes, what is it?\p"
	.string "Hm...\n"
	.string "It’s raining heavily?\p"
	.string "Good... That should have happened.\n"
	.string "That is why we awakened Kyogre,\l"
	.string "to realize Team Aqua’s vision of\l"
	.string "expanding the sea.\p"
	.string "What?!\p"
	.string "It’s raining far harder than we\n"
	.string "envisioned? You’re in danger?\p"
	.string "That can’t be...\n"
	.string "That’s just not possible...\p"
	.string "Hold your position and monitor the\n"
	.string "situation!$"

UnknownString_81B45C6: @ 81B45C6
	.string "Archie: There’s something wrong...\p"
	.string "The Red Orb is supposed to awaken\n"
	.string "and control Kyogre...\p"
	.string "But... Why?\n"
	.string "Why did Kyogre disappear?\p"
	.string "Why?!$"

UnknownString_81B464D: @ 81B464D
	.string "Maxie: What have you wrought?\p"
	.string "Archie... You’ve finally awoken Kyogre,\n"
	.string "haven’t you?\p"
	.string "What will happen to the world if this\n"
	.string "downpour continues for all eternity?\p"
	.string "The world’s landmass will drown in\n"
	.string "the deepening sea...$"

UnknownString_81B4723: @ 81B4723
	.string "Archie: What are you saying?\p"
	.string "The Red Orb should let me control\n"
	.string "Kyogre...\l"
	.string "That can’t be possible...$"

UnknownString_81B4786: @ 81B4786
	.string "Maxie: We don’t have the time to\n"
	.string "argue about it here!\p"
	.string "Get outside and see for yourself!\p"
	.string "See if what you’ve wrought is the\n"
	.string "world that you desired!$"

UnknownString_81B4818: @ 81B4818
	.string "Maxie: {PLAYER}{KUN}, come on, you have\n"
	.string "to get out of here, too!$"
