FallarborTown_ContestLobby_Text_1A5DFC:: @ 81A5DFC
	.string "Hello, there!\p"
	.string "We’re accepting registrations for\n"
	.string "{STR_VAR_1} Rank Pokémon Contests.$"

FallarborTown_ContestLobby_Text_1A5E46:: @ 81A5E46
	.string "Would you like to enter your Pokémon\n"
	.string "in our Contests?$"

FallarborTown_ContestLobby_Text_1A5E7C:: @ 81A5E7C
	.string "Which topic would you like?$"

FallarborTown_ContestLobby_Text_1A5E98:: @ 81A5E98
	.string "A Pokémon Contest involves four\n"
	.string "Trainer entering one Pokémon each\l"
	.string "in competitive judging.\p"
	.string "A Contest has two stages of judging,\n"
	.string "primary and secondary.\p"
	.string "Primary judging is a popularity poll\n"
	.string "involving the audience.\p"
	.string "Secondary judging features appeals\n"
	.string "by the Pokémon using their moves.\p"
	.string "Plan appeals carefully to earn the\n"
	.string "most attention of the Judge and\l"
	.string "excite the audience.\l"
	.string "Do your best to stand out.\p"
	.string "The primary and secondary scores are\n"
	.string "added at the end.\p"
	.string "The Pokémon garnering the highest\n"
	.string "score is declared the winner.$"

FallarborTown_ContestLobby_Text_1A609B:: @ 81A609B
	.string "There are five kinds of Contests.\p"
	.string "Cool, Beauty, Cute, Smart, and\n"
	.string "Tough are the five categories.\p"
	.string "Choose the Contest that is right for\n"
	.string "the Pokémon you plan to enter.$"

FallarborTown_ContestLobby_Text_1A613F:: @ 81A613F
	.string "There are four ranks of Pokémon\n"
	.string "Contests.\p"
	.string "Normal, Super, Hyper and Master\n"
	.string "are the four ranks.\p"
	.string "In the Normal Rank, any Pokémon may\n"
	.string "enter.\p"
	.string "Any Pokémon that won a Normal Rank\n"
	.string "Contest may move up the Super Rank in\l"
	.string "the same category.\p"
	.string "In the same way, a Super Rank winner\n"
	.string "can move up to the Hyper Rank, and a\l"
	.string "Hyper Rank winner can advance to the\l"
	.string "Master Rank in the same category.\p"
	.string "A Pokémon that won in the Master Rank\n"
	.string "may compete in the Master Rank as\l"
	.string "often as its Trainer wants.$"

FallarborTown_ContestLobby_Text_1A6319:: @ 81A6319
	.string "Which Pokémon would you like to enter?$"

FallarborTown_ContestLobby_Text_1A6340:: @ 81A6340
	.string "Anyone with a Contest Pass may enter.\p"
	.string "You may obtain a Contest PASS at the\n"
	.string "Normal Rank Contest Hall in\l"
	.string "Verdanturf Town free of charge.\p"
	.string "Please obtain a Contest Pass and\n"
	.string "come again.$"

LilycoveCity_ContestLobby_Text_1A63F4:: @ 81A63F4
	.string "I accept registrations only from four\n"
	.string "linked players for a Pokémon Contest.\p"
	.string "Anyone with a Contest Pass may enter.\p"
	.string "You may obtain a Contest PASS at the\n"
	.string "Normal Rank Contest Hall in\l"
	.string "Verdanturf Town free of charge.\p"
	.string "Please obtain a Contest Pass and\n"
	.string "come again.$"

FallarborTown_ContestLobby_Text_1A64F4:: @ 81A64F4
	.string "Anyone with a Contest Pass may enter.\p"
	.string "If you don’t have one, I can issue one\n"
	.string "for you right now.\p"
	.string "Would you like me to issue you a\n"
	.string "Contest Pass?$"

FallarborTown_ContestLobby_Text_1A6583:: @ 81A6583
	.string "Here you go!$"

FallarborTown_ContestLobby_Text_1A6590:: @ 81A6590
	.string "Oh?\p"
	.string "We’ve already issued you a Contest\n"
	.string "Pass, {PLAYER}.\p"
	.string "Please come back with your Contest\n"
	.string "Pass.$"

FallarborTown_ContestLobby_Text_1A65EA:: @ 81A65EA
	.string "Please visit whenever you would like\n"
	.string "to enter a Contest.$"

FallarborTown_ContestLobby_Text_1A6623:: @ 81A6623
	.string "Which Contest would you like to enter?$"

FallarborTown_ContestLobby_Text_1A664A:: @ 81A664A
LilycoveCity_ContestLobby_Text_1A664A:: @ 81A664A
	.string "I’m terribly sorry, but your Pokémon\n"
	.string "is not qualified to compete at this\l"
	.string "rank yet...$"

FallarborTown_ContestLobby_Text_1A669F:: @ 81A669F
LilycoveCity_ContestLobby_Text_1A669F:: @ 81A669F
	.string "I’m sorry, but an Egg cannot take part\n"
	.string "in a Pokémon Contest.$"

FallarborTown_ContestLobby_Text_1A66DC:: @ 81A66DC
LilycoveCity_ContestLobby_Text_1A66DC:: @ 81A66DC
	.string "Your Pokémon appears to be in no\n"
	.string "condition to take part in a Contest...$"

FallarborTown_ContestLobby_Text_1A6724:: @ 81A6724
	.string "Oh, but that Ribbon...\p"
	.string "Your Pokémon has won this Contest\n"
	.string "before, hasn’t it?\p"
	.string "Would you like to enter it in this\n"
	.string "Contest anyway?$"

FallarborTown_ContestLobby_Text_1A67A3:: @ 81A67A3
LilycoveCity_ContestLobby_Text_1A67A3:: @ 81A67A3
	.string "Is that your Contest Pokémon?$"

FallarborTown_ContestLobby_Text_1A67C1:: @ 81A67C1
	.string "Okay, your Pokémon will be entered\n"
	.string "in this Contest.\p"
	.string "Your Pokémon is Entry No. 4.\n"
	.string "The Contest will begin shortly.$"

FallarborTown_ContestLobby_Text_1A6832:: @ 81A6832
LilycoveCity_ContestLobby_Text_1A6832:: @ 81A6832
SlateportCity_ContestLobby_Text_1A6832:: @ 81A6832
VerdanturfTown_ContestLobby_Text_1A6832:: @ 81A6832
	.string "Please come in through here.\n"
	.string "Good luck!$"

FallarborTown_ContestLobby_Text_1A685A:: @ 81A685A
	.string "Congratulations! Your Pokémon is the\n"
	.string "Contest winner!\p"
	.string "We have your prize right here.\n"
	.string "Please, right this way!$"

FallarborTown_ContestLobby_Text_1A68C6:: @ 81A68C6
	.string "Please come back for your prize\n"
	.string "later on.$"

LinkContestRoom1_Text_1A68F0:: @ 81A68F0
	.string "MC: Hello! We’re just getting started\n"
	.string "with a {STR_VAR_3} Rank Pokémon\l"
	.string "{STR_VAR_2} Contest!\p"
	.string "The participating Trainer and their\n"
	.string "Pokémon are as follows:$"

LinkContestRoom1_Text_1A6976:: @ 81A6976
	.string "MC: Hello! We’re just getting started\n"
	.string "with a 4-player linked Pokémon\l"
	.string "{STR_VAR_2} Contest!\p"
	.string "The participating Trainer and their\n"
	.string "Pokémon are as follows:$"

LinkContestRoom1_Text_1A6A04:: @ 81A6A04
	.string "MC: Entry No. {STR_VAR_2}!\n"
	.string "{STR_VAR_1}’s {STR_VAR_3}!$"

LinkContestRoom1_Text_1A6A1F:: @ 81A6A1F
	.string "MC: We’ve just seen the four Pokémon\n"
	.string "contestants.\p"
	.string "Now it’s time for primary judging!\p"
	.string "The audience will vote on their\n"
	.string "favorite Pokémon contestants.\p"
	.string "Without any further ado, let the\n"
	.string "voting begin!$"

LinkContestRoom1_Text_1A6AE1:: @ 81A6AE1
	.string "Voting under way...$"

LinkContestRoom1_Text_1A6AF5:: @ 81A6AF5
	.string "Voting is now complete!\p"
	.string "While the votes are being tallied,\n"
	.string "let’s move on to secondary judging!\p"
	.string "The second stage of judging is the\n"
	.string "much anticipated appeal time!\p"
	.string "May the contestants amaze us with\n"
	.string "superb appeals of dazzling moves!\p"
	.string "Let’s see a little enthusiasm!\n"
	.string "Let’s appeal!$"

LinkContestRoom1_Text_1A6C06:: @ 81A6C06
	.string "MC: That’s it for judging!$"

LinkContestRoom1_Text_1A6C21:: @ 81A6C21
	.string "Thank you all for a most wonderful\n"
	.string "display of quality appeals!\p"
	.string "This concludes all judging!\n"
	.string "Thank you for your fine efforts!$"

LinkContestRoom1_Text_1A6C9D:: @ 81A6C9D
	.string "Now, all that remains is the pulse-\n"
	.string "pounding proclamation of the winner.\p"
	.string "The Judge looks ready to make the\n"
	.string "announcement!$"

LinkContestRoom1_Text_1A6D16:: @ 81A6D16
	.string "Judge: I will now declare the winner!$"

LinkContestRoom1_Text_1A6D3C:: @ 81A6D3C
	.string "MC: Entry No. {STR_VAR_2}!\p"
	.string "{STR_VAR_3} and {STR_VAR_1},\n"
	.string "congratulations!$"

LinkContestRoom1_Text_1A6D6A:: @ 81A6D6A
	.string "We confer on you this Ribbon as your\n"
	.string "prize!$"

LinkContestRoom1_Text_1A6D96:: @ 81A6D96
	.string "{PLAYER} received a Ribbon.$"

LinkContestRoom1_Text_1A6DAC:: @ 81A6DAC
	.string "{PLAYER} put the Ribbon on\n"
	.string "{STR_VAR_1}.$"

LinkContestRoom1_Text_1A6DC5:: @ 81A6DC5
	.string "MC: Here you are!\n"
	.string "Please accept your prize!$"

LinkContestRoom1_Text_1A6DF1:: @ 81A6DF1
	.string "MC: Congratulations!\n"
	.string "Please do compete again!$"

LinkContestRoom1_Text_1A6E1F:: @ 81A6E1F
	.string "Please pick up your prize at the\n"
	.string "reception counter later.\l"
	.string "Please do compete again!$"
