gLandmarkName_FlowerShop::
	.string "Flower Shop$"

gLandmarkName_PetalburgWoods::
	.string "Petalburg Woods$"

gLandmarkName_MrBrineysCottage::
	.string "Mr. Briney’s Cottage$"

gLandmarkName_AbandonedShip::
	.string "Abandoned Ship$"

gLandmarkName_SeashoreHouse::
	.string "Seashore House$"

gLandmarkName_SlateportBeach::
	.string "Slateport Beach$"

gLandmarkName_CyclingRoad::
	.string "Cycling Road$"

gLandmarkName_NewMauville::
	.string "New Mauville$"

gLandmarkName_TrickHouse::
	.string "Trick House$"

gLandmarkName_OldLadysRestShop::
	.string "Old Lady’s Rest Stop$"

gLandmarkName_Desert::
	.string "Desert$"

gLandmarkName_WinstrateFamily::
	.string "The Winstrate's House$"

gLandmarkName_CableCar::
	.string "Cable Car$"

gLandmarkName_GlassWorkshop::
	.string "Glass Workshop$"

gLandmarkName_WeatherInstitute::
	.string "Weather Institute$"

gLandmarkName_MeteorFalls::
	.string "Meteor Falls$"

gLandmarkName_TunnelersRestHouse::
	.string "Tunneler’s Rest House$"

gLandmarkName_RusturfTunnel::
	.string "Rustarf Tunnel$"

gLandmarkName_PokemonDayCare::
	.string "Day Care$"

gLandmarkName_SafariZoneEntrance::
	.string "Safari Zone Entrance$"

gLandmarkName_MtPyre::
	.string "Mt. Pyre$"

gLandmarkName_ShoalCave::
	.string "Shoal Cave$"

gLandmarkName_SeafloorCavern::
	.string "Seafloor Cavern$"

gLandmarkName_GraniteCave::
	.string "Granite Cave$"

gLandmarkName_OceanCurrent::
	.string "Ocean Current$"

gLandmarkName_LanettesHouse::
	.string "Lanette’s House$"

gLandmarkName_FieryPath::
	.string "Fiery Path$"

gLandmarkName_JaggedPass::
	.string "Jagged Pass$"

gLandmarkName_SkyPillar::
	.string "Sky Pillar$"

gLandmarkName_BerryMastersHouse::
	.string "Berry Master’s House$"

gLandmarkName_IslandCave::
	.string "Island Cave$"

gLandmarkName_DesertRuins::
	.string "Desert Ruins$"

gLandmarkName_ScorchedSlab::
	.string "Scorched Slab$"

gLandmarkName_AncientTomb::
	.string "Ancient Tomb$"

gLandmarkName_SealedChamber::
	.string "Sealed Chamber$"

gLandmarkName_FossilManiacsHouse::
	.string "Fossil Maniac’s House$"

gLandmarkName_HuntersHouse::
	.string "Shard Hunter’s House$"
