MtPyre_Summit_Text_1B5CFD:: @ 81B5CFD
	.string "I’ll show you exactly how scary\n"
	.string "Team Magma can be!$"

MtPyre_Summit_Text_1B5D30:: @ 81B5D30
	.string "So you think you can stand up alone\n"
	.string "to Team Magma’s might...$"

MtPyre_Summit_Text_1B5D6D:: @ 81B5D6D
	.string "Yeah, so you are strong...\n"
	.string "But there’re a lot of us!$"

MtPyre_Summit_Text_1B5DA2:: @ 81B5DA2
	.string "What’s up with you?\n"
	.string "What does a single kid expect to do?$"

MtPyre_Summit_Text_1B5DDB:: @ 81B5DDB
	.string "Dang...\n"
	.string "Too strong...$"

MtPyre_Summit_Text_1B5DF1:: @ 81B5DF1
	.string "You don’t know anything.\n"
	.string "Quit messing around with us!$"

MtPyre_Summit_Text_1B5E27:: @ 81B5E27
	.string "Hey, I remember you from Mt. Chimney!\n"
	.string "It’s payback time!$"

MtPyre_Summit_Text_1B5E60:: @ 81B5E60
	.string "Urgggh...\n"
	.string "Beaten by some kid again!$"

MtPyre_Summit_Text_1B5E84:: @ 81B5E84
	.string "Heh, it doesn’t matter!\n"
	.string "We bought ourselves some time!\p"
	.string "The BOSS should have snatched what\n"
	.string "he was after!$"

MtPyre_Summit_Text_1B5EEC:: @ 81B5EEC
	.string "Maxie: Not you again...\p"
	.string "You’ve impeded our plans repeatedly,\n"
	.string "but this time you’re too late.\p"
	.string "The Blue Orb that rested atop\n"
	.string "Mt. Pyre...\l"
	.string "I, Maxie, claim it as mine!\p"
	.string "Fufufu... Finally, I can realize my\n"
	.string "grand design...\p"
	.string "Come on, crew!\n"
	.string "It’s Slateport next!$"

MtPyre_Summit_Text_1B5FE6:: @ 81B5FE6
	.string "Oh, no...\n"
	.string "This cannot happen...\p"
	.string "How could they take the Blue Orb?\p"
	.string "The Blue Orb and Red Orb must never\n"
	.string "be separated. They belong together.\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "Hmm...\p"
	.string "Fine!\n"
	.string "You take the remaining Red Orb.\p"
	.string "Please take after that foul man and\n"
	.string "get the other Orb back!$"

MtPyre_Summit_Text_1B60F9:: @ 81B60F9
	.string "The Red Orb you have been entrusted\n"
	.string "with and the stolen Blue Orb...\p"
	.string "They must never be apart...\n"
	.string "Something terrible will happen...$"

MtPyre_Summit_Text_1B617B:: @ 81B617B
	.string "So...\n"
	.string "Groudon has awoken...\p"
	.string "The wondrous Orb that is said to have\n"
	.string "becalmed the raging Groudon...\l"
	.string "It is the Red Orb you bear.\p"
	.string "That Red Orb was found buried inside\n"
	.string "the Cave of Origin in Sootopolis...\p"
	.string "There is perhaps a link between\n"
	.string "Groudon and the Cave of Origin...$"

MtPyre_Summit_Text_1B6283:: @ 81B6283
	.string "That man, he returned the Blue Orb.\p"
	.string "Are you going to return the Red Orb\n"
	.string "to its rightful place, too?$"

MtPyre_Summit_Text_1B62E7:: @ 81B62E7
	.string "What’s that?!\p"
	.string "If the balance is not restored, there\n"
	.string "is no telling what could happen.\p"
	.string "You will return the Red Orb to its\n"
	.string "rightful place, yes?$"

UnknownString_81B6374: @ 81B6374
	.string "{PLAYER} handed the Red Orb to the\n"
	.string "old woman.$"

MtPyre_Summit_Text_1B639C:: @ 81B639C
	.string "Yes...\n"
	.string "The two Orbs should remain here.\p"
	.string "It is how it should be for the good\n"
	.string "of all Hoenn...$"

MtPyre_Summit_Text_1B63F8:: @ 81B63F8
	.string "The spirit of the land...\p"
	.string "That is what Groudon is said to be in\n"
	.string "Pokémon form...\p"
	.string "In the same manner that we and Pokémon\n"
	.string "have life, this very land is alive...\p"
	.string "Groudon has taught us that...$"

MtPyre_Summit_Text_1B64B3:: @ 81B64B3
	.string "Mt. Pyre is where we calm the spirits\n"
	.string "of Pokémon that have passed on...\p"
	.string "This is a high place where one can\n"
	.string "see all of Hoenn...\p"
	.string "The disembodied spirits of Pokémon\n"
	.string "must find solace here...\p"
	.string "Is it coincidence that you are here...\p"
	.string "Will you hear out my tale? A tale long\n"
	.string "told in the Hoenn region?$"

MtPyre_Summit_Text_1B65D6:: @ 81B65D6
	.string "It happened long, long ago...\p"
	.string "The world was wracked by a ferocious\n"
	.string "clash between the Pokémon of the land\l"
	.string "and the Pokémon of the sea...\p"
	.string "The Pokémon of the land raised\n"
	.string "mountains and created continents...\p"
	.string "The Pokémon of the sea raised huge\n"
	.string "waves and carved out oceans...\p"
	.string "Their fierce duel raged without end.\p"
	.string "The world was engulfed in vicious\n"
	.string "storms and massive infernos.\p"
	.string "The Red Orb and the Blue Orb brought\n"
	.string "an end to the calamity.\p"
	.string "Light poured from the two Orbs and\n"
	.string "becalmed the enraged adversaries.\p"
	.string "The pair, made docile, burrowed deep\n"
	.string "under the ground where eventually\l"
	.string "they disappeared...$"

MtPyre_Summit_Text_1B6823:: @ 81B6823
	.string "I see...\n"
	.string "Well, that, too, is fine...$"

MtPyre_Summit_Text_1B6848:: @ 81B6848
	.string "Maxie: You...\n"
	.string "So you stopped Groudon...\p"
	.string "I shouldn’t be surprised...\p"
	.string "I understand now that humans cannot\n"
	.string "freely control the balance between\l"
	.string "the land and the sea...\p"
	.string "So I have come to return the\n"
	.string "Blue Orb...\p"
	.string "I doubt that we will cross paths again...\n"
	.string "Farewell...$"
