gTextStoryteller_Introduction:: @ 81AECC6
	.string "I’m the Storyteller.\n"
	.string "I’ll tell you tales of legendary\l"
	.string "Trainers.\p"
	.string "Will you hear my tale?$"

gTextStoryteller_OhIFeelStifled:: @ 81AED1D
	.string "Oh...\n"
	.string "I feel stifled...$"

gTextStoryteller_WhichTale:: @ 81AED35
	.string "I know of these legends.\n"
	.string "Which tale will you have me tell?$"

gTextStoryteller_ButIKnowOfNoLegendaryTrainers:: @ 81AED70
	.string "But, I know of no legendary Trainers.\n"
	.string "Hence, I know no tales.\p"
	.string "Where does one find a Trainer worthy\n"
	.string "of a legendary tale?$"

gTextStoryteller_BirthOfANewLegend:: @ 81AEDE8
	.string "What’s that?!\n"
	.string "You... You...\p"
	.string "{STR_VAR_2}\n"
	.string "{STR_VAR_1} time(s)?!\p"
	.string "That is indeed magnificent!\n"
	.string "It’s the birth of a new legend!$"

gTextStoryteller_CouldThereBeOtherTrainers:: @ 81AEE50
	.string "It gets me thinking, could there be\n"
	.string "other Trainers with more impressive\l"
	.string "legends awaiting discovery?$"

gTextStoryteller_HaveYouAnyTales:: @ 81AEEB4
	.string "Are you a Trainer?\p"
	.string "Then tell me, have you any tales that\n"
	.string "are even remotely legendary?$"

gTextStoryteller_HearAnotherLegendaryTale:: @ 81AEF0A
	.string "Incidentally... Would you care to hear\n"
	.string "another legendary tale?$"

gTextStoryteller_ImNotSatisfied:: @ 81AEF49
	.string "Hmm...\n"
	.string "I’m not satisfied...\p"
	.string "I wish you would bring me news worthy\n"
	.string "of being called a legend.$"

gTextStoryteller_WishMorePeopleWould:: @ 81AEFA5
	.string "I wish more people would be interested\n"
	.string "in hearing my epic tales of legendary\l"
	.string "TrainerS.$"

gTextStoryteller_Story1Title:: @ 81AEFFC
	.string "The Save-Happy Trainer$"

gTextStoryteller_Story1Action:: @ 81AF013
	.string "Saved the game$"

gTextStoryteller_Story1Text:: @ 81AF022
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer saved the game\n"
	.string "{STR_VAR_1} times!\p"
	.string "A more cautious Trainer than\n"
	.string "{STR_VAR_3} one will never find!$"

gTextStoryteller_Story2Title:: @ 81AF0A3
	.string "The Trendsetter Trainer$"

gTextStoryteller_Story2Action:: @ 81AF0BB
	.string "Started trends$"

gTextStoryteller_Story2Text:: @ 81AF0CA
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer started new trends\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is setting trends for all\n"
	.string "the Hoenn region!$"

gTextStoryteller_Story3Title:: @ 81AF149
	.string "The Berry-Planting Trainer$"

gTextStoryteller_Story3Action:: @ 81AF164
	.string "Planted Berries$"

gTextStoryteller_Story3Text:: @ 81AF174
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer planted Berries\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a legendary lover of\n"
	.string "Berries!$"

gTextStoryteller_Story4Title:: @ 81AF1E5
	.string "The Bike-Loving Trainer$"

gTextStoryteller_Story4Action:: @ 81AF1FD
	.string "Traded Bikes$"

gTextStoryteller_Story4Text:: @ 81AF20A
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer swapped Bikes\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must love Bikes deeply\n"
	.string "and passionately!$"

gTextStoryteller_Story5Title:: @ 81AF281
	.string "The Interviewed Trainer$"

gTextStoryteller_Story5Action:: @ 81AF299
	.string "Got interviewed$"

gTextStoryteller_Story5Text:: @ 81AF2A9
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer got interviewed\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a Trainer who’s\n"
	.string "attracting much attention!$"

gTextStoryteller_Story6Title:: @ 81AF32C
	.string "The Battle-Happy Trainer$"

gTextStoryteller_Story6Action:: @ 81AF345
	.string "Battled$"

gTextStoryteller_Story6Text:: @ 81AF34D
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer battled {STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a Trainer who can\n"
	.string "never refuse a chance to battle!$"

gTextStoryteller_Story7Title:: @ 81AF3D0
	.string "The Pokémon-Catching Trainer$"

gTextStoryteller_Story7Action:: @ 81AF3ED
	.string "Caught Pokémon$"

gTextStoryteller_Story7Text:: @ 81AF3FC
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer caught\n"
	.string "{STR_VAR_1} Pokémon!\p"
	.string "{STR_VAR_3} is a legendary catcher of\n"
	.string "wild Pokémon!$"

gTextStoryteller_Story8Title:: @ 81AF46D
	.string "The Fishing Trainer$"

gTextStoryteller_Story8Action:: @ 81AF481
	.string "Caught Pokémon with a Rod$"

gTextStoryteller_Story8Text:: @ 81AF49B
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer caught\n"
	.string "{STR_VAR_1} Pokémon while fishing!\p"
	.string "{STR_VAR_3} is a legendary fishing\n"
	.string "expert!$"

gTextStoryteller_Story9Title:: @ 81AF511
	.string "The Egg-Warming Trainer$"

gTextStoryteller_Story9Action:: @ 81AF529
	.string "Hatched Eggs$"

gTextStoryteller_Story9Text:: @ 81AF536
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer hatched {STR_VAR_1} Pokémon\n"
	.string "from Eggs!\p"
	.string "{STR_VAR_3} is a legendary warmer\n"
	.string "of Eggs!$"

gTextStoryteller_Story10Title:: @ 81AF5A9
	.string "The Evolver Trainer$"

gTextStoryteller_Story10Action:: @ 81AF5BD
	.string "Evolved Pokémon$"

gTextStoryteller_Story10Text:: @ 81AF5CD
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer made {STR_VAR_1} Pokémon\n"
	.string "evolve!\p"
	.string "{STR_VAR_3} is the ultimate evolver\n"
	.string "of Pokémon!$"

gTextStoryteller_Story11Title:: @ 81AF63F
	.string "The Pokémon Center-Loving Trainer$"

gTextStoryteller_Story11Action:: @ 81AF661
	.string "Used Pokémon Centers$"

gTextStoryteller_Story11Text:: @ 81AF676
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer healed Pokémon\n"
	.string "{STR_VAR_1} times at Pokémon Centers!\p"
	.string "There could be no greater lover of\n"
	.string "Pokémon Centers than {STR_VAR_3}!$"

gTextStoryteller_Story12Title:: @ 81AF711
	.string "The Homebody Trainer$"

gTextStoryteller_Story12Action:: @ 81AF726
	.string "Rested Pokémon at home$"

gTextStoryteller_Story12Text:: @ 81AF73D
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer healed Pokémon\n"
	.string "{STR_VAR_1} times at home!\p"
	.string "There could be no more of a homebody\n"
	.string "than {STR_VAR_3}!$"

gTextStoryteller_Story13Title:: @ 81AF7BF
	.string "The Safari-Loving Trainer$"

gTextStoryteller_Story13Action:: @ 81AF7D9
	.string "Entered the Safari Zone$"

gTextStoryteller_Story13Text:: @ 81AF7F1
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer went into the Safari Zone\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a Trainer whose wild side\n"
	.string "must come out in the Safari Zone!$"

gTextStoryteller_Story14Title:: @ 81AF88A
	.string "The Cut-Frenzy Trainer$"

gTextStoryteller_Story14Action:: @ 81AF8A1
	.string "Used Cut$"

gTextStoryteller_Story14Text:: @ 81AF8AA
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer used Cut$n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a Trainer who just must\n"
	.string "love to Cut!$"

gTextStoryteller_Story15Title:: @ 81AF91B
	.string "The Rock-Smashing Trainer$"

gTextStoryteller_Story15Action:: @ 81AF935
	.string "Smashed rocks$"

gTextStoryteller_Story15Text:: @ 81AF943
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer used Rock Smash\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a Trainer who\n"
	.string "can’t leave a stone unsmashed!$"

gTextStoryteller_Story16Title:: @ 81AF9C8
	.string "The Move-Loving Trainer$"

gTextStoryteller_Story16Action:: @ 81AF9E0
	.string "Moved the Secret Base$"

gTextStoryteller_Story16Text:: @ 81AF9F6
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer moved the Secret Base\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a Trainer who loves\n"
	.string "to move houses often!$"

gTextStoryteller_Story17Title:: @ 81AFA79
	.string "The Splash-Happy Trainer$"

gTextStoryteller_Story17Action:: @ 81AFA92
	.string "Used Splash$"

gTextStoryteller_Story17Text:: @ 81AFA9E
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer used Splash\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a Trainer who must love\n"
	.string "splashing around!$"

gTextStoryteller_Story18Title:: @ 81AFB17
	.string "The Tenacious Trainer$"

gTextStoryteller_Story18Action:: @ 81AFB2D
	.string "Resorted to using Struggle$"

gTextStoryteller_Story18Text:: @ 81AFB48
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer had to rely on Struggle\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a tenacious Trainer\n"
	.string "who never gives in to adversity!$"

gTextStoryteller_Story19Title:: @ 81AFBD8
	.string "The Slot Champ$"

gTextStoryteller_Story19Action:: @ 81AFBE7
	.string "Won the jackpot on the slots$"

gTextStoryteller_Story19Text:: @ 81AFC04
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer won the jackpot on\n"
	.string "the slots {STR_VAR_1} times.\p"
	.string "{STR_VAR_3} is a Trainer who was lucky\n"
	.string "on the slots!$"

gTextStoryteller_Story20Title:: @ 81AFC8A
	.string "The Roulette Champ$"

gTextStoryteller_Story20Action:: @ 81AFC9D
	.string "Had consecutive Roulette wins of$"

gTextStoryteller_Story20Text:: @ 81AFCBE
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer won in Roulette\n"
	.string "{STR_VAR_1} times in a row.\p"
	.string "{STR_VAR_3} was lucky when the ball\n"
	.string "bounced in Roulette!$"

gTextStoryteller_Story21Title:: @ 81AFD44
	.string "The Battle Tower Challenger$"

gTextStoryteller_Story21Action:: @ 81AFD60
	.string "Took the Battle Tower challenge$"

gTextStoryteller_Story21Text:: @ 81AFD80
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer took the Battle Tower\n"
	.string "challenge {STR_VAR_1} times!\p"
	.string "{STR_VAR_3} is a Trainer who aspires\n"
	.string "for excellence in the Battle Tower!$"

gTextStoryteller_Story22Title:: @ 81AFE1D
	.string "The Blend-Loving Trainer$"

gTextStoryteller_Story22Action:: @ 81AFE36
	.string "Made {POKEBLOCK}S$"

gTextStoryteller_Story22Text:: @ 81AFE42
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer made {POKEBLOCK}s\n"
	.string "{STR_VAR_1} times!\p"
	.string "There is none better at using a Berry\n"
	.string "Blender than {STR_VAR_3}!$"

gTextStoryteller_Story23Title:: @ 81AFEC2
	.string "The Contest-Loving Trainer$"

gTextStoryteller_Story23Action:: @ 81AFEDD
	.string "Entered Contests$"

gTextStoryteller_Story23Text:: @ 81AFEEE
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer entered Contests\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must love showing off\n"
	.string "Pokémon to others!$"

gTextStoryteller_Story24Title:: @ 81AFF68
	.string "The Contest Master$"

gTextStoryteller_Story24Action:: @ 81AFF7B
	.string "Won CONTESTS$"

gTextStoryteller_Story24Text:: @ 81AFF88
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer won Contests\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be an incredible\n"
	.string "Contest master!$"

gTextStoryteller_Story25Title:: @ 81AFFFB
	.string "The Happy Shopper$"

gTextStoryteller_Story25Action:: @ 81B000D
	.string "Shopped$"

gTextStoryteller_Story25Text:: @ 81B0015
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer bought items in shops\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be one of those\n"
	.string "people who are born to shop.$"

gTextStoryteller_Story26Title:: @ 81B009D
	.string "The Item-Finding Trainer$"

gTextStoryteller_Story26Action:: @ 81B00B6
	.string "Used an Itemfinder$"

gTextStoryteller_Story26Text:: @ 81B00C9
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer used an Itemfinder\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must enjoy scouring the\n"
	.string "ground for hidden items!$"

gTextStoryteller_Story27Title:: @ 81B014D
	.string "The Rain-Soaked Trainer$"

gTextStoryteller_Story27Action:: @ 81B0165
	.string "Got rained on$"

gTextStoryteller_Story27Text:: @ 81B0173
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer got soaked by rain\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3}’s charisma must even\n"
	.string "attract rain!$"

gTextStoryteller_Story28Title:: @ 81B01E9
	.string "The Avid Pokédex Reader$"

gTextStoryteller_Story28Action:: @ 81B0201
	.string "Checked a Pokédex$"

gTextStoryteller_Story28Text:: @ 81B0213
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer checked a Pokédex\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must love inspecting\n"
	.string "Pokémon in a Pokédex!$"

gTextStoryteller_Story29Title:: @ 81B0290
	.string "The Ribbon Collector$"

gTextStoryteller_Story29Action:: @ 81B02A5
	.string "Received Ribbons$"

gTextStoryteller_Story29Text:: @ 81B02B6
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer received Ribbons\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a Trainer who\n"
	.string "loves to collect Ribbons!$"

gTextStoryteller_Story30Title:: @ 81B0337
	.string "The Ledge-Jumping Trainer$"

gTextStoryteller_Story30Action:: @ 81B0351
	.string "Jumped down ledges$"

gTextStoryteller_Story30Text:: @ 81B0364
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer jumped down ledges\n"
	.string "{STR_VAR_1} times!\p"
	.string "If there’s a ledge to be jumped,\n"
	.string "{STR_VAR_3} can’t ignore it!$"

gTextStoryteller_Story31Title:: @ 81B03E9
	.string "The Legendary TV Viewer$"

gTextStoryteller_Story31Action:: @ 81B0401
	.string "Watched TV$"

gTextStoryteller_Story31Text:: @ 81B040C
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer watched TV\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must love watching TV!$"

gTextStoryteller_Story32Title:: @ 81B046E
	.string "The Time-Conscious Trainer$"

gTextStoryteller_Story32Action:: @ 81B0489
	.string "Checked the time$"

gTextStoryteller_Story32Text:: @ 81B049A
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer checked the time\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a punctual Trainer\n"
	.string "who’s conscious of the time.$"

gTextStoryteller_Story33Title:: @ 81B0523
	.string "The Pokémon Lottery Wizard$"

gTextStoryteller_Story33Action:: @ 81B053E
	.string "Won Pokémon Lotteries$"

gTextStoryteller_Story33Text:: @ 81B0554
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer won Pokémon Lotteries\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must have many friends\n"
	.string "to trade Pokémon with!$"

gTextStoryteller_Story34Title:: @ 81B05D8
	.string "The Day Care-Using Trainer$"

gTextStoryteller_Story34Action:: @ 81B05F3
	.string "Left Pokémon at the Day Care$"

gTextStoryteller_Story34Text:: @ 81B0610
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer left Pokémon with the\n"
	.string "Day Care {STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a real go-getter\n"
	.string "who raises Pokémon aggressively!$"

gTextStoryteller_Story35Title:: @ 81B06A9
	.string "The Cable Car-Loving Trainer$"

gTextStoryteller_Story35Action:: @ 81B06C6
	.string "Rode the Cable Car$"

gTextStoryteller_Story35Text:: @ 81B06D9
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer rode the Cable Car\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a busy Trainer\n"
	.string "who’s up and down all the time!$"

gTextStoryteller_Story36Title:: @ 81B0763
	.string "The Hot Spring-Loving Trainer$"

gTextStoryteller_Story36Action:: @ 81B0781
	.string "Bathed in hot springs$"

gTextStoryteller_Story36Text:: @ 81B0797
	.string "This is a tale of a Trainer\n"
	.string "named {STR_VAR_3}.\p"
	.string "This Trainer bathed in hot springs\n"
	.string "{STR_VAR_1} times!\p"
	.string "{STR_VAR_3} must be a Trainer with\n"
	.string "baby-smooth skin!$"
