gEasyChatGroupName_Pokemon:: @ 842C7DB
	.string "Pokémon$"

gEasyChatGroupName_Trainer:: @ 842C7E3
	.string "Trainer$"

gEasyChatGroupName_Status:: @ 842C7EB
	.string "Status$"

gEasyChatGroupName_Battle:: @ 842C7F2
	.string "Battle$"

gEasyChatGroupName_Greetings:: @ 842C7F9
	.string "Greetings$"

gEasyChatGroupName_People:: @ 842C803
	.string "People$"

gEasyChatGroupName_Voices:: @ 842C80A
	.string "Voices$"

gEasyChatGroupName_Speech:: @ 842C811
	.string "Speech$"

gEasyChatGroupName_Endings:: @ 842C818
	.string "Endings$"

gEasyChatGroupName_Feelings:: @ 842C820
	.string "Feelings$"

gEasyChatGroupName_Conditions:: @ 842C829
	.string "Conditions$"

gEasyChatGroupName_Actions:: @ 842C834
	.string "Actions$"

gEasyChatGroupName_Lifestyle:: @ 842C83C
	.string "Lifestyle$"

gEasyChatGroupName_Hobbies:: @ 842C846
	.string "Hobbies$"

gEasyChatGroupName_Time:: @ 842C84E
	.string "Time$"

gEasyChatGroupName_Misc:: @ 842C853
	.string "Misc.$"

gEasyChatGroupName_Adjectives:: @ 842C859
	.string "Adjectives$"

gEasyChatGroupName_Events:: @ 842C864
	.string "Events$"

gEasyChatGroupName_Move1:: @ 842C86B
	.string "Move 1$"

gEasyChatGroupName_Move2:: @ 842C872
	.string "Move 2$"

gEasyChatGroupName_TrendySaying:: @ 842C879
	.string "Trendy Saying$"

gEasyChatGroupName_Pokemon2:: @ 842C887
	.string "Pokémon2$"
