	.ifndef GERMAN
MossdeepCity_Text_1690A9:: @ 81690A9
	.string "I got this from STEVEN, but I don't\n"
	.string "know what it's good for.\p"
	.string "I think it's called KING'S ROCK.\n"
	.string "Do you want it?$"

MossdeepCity_Text_169117:: @ 8169117
	.string "Why would you want it?\n"
	.string "You're weird.\p"
	.string "You can keep it, but keep it a secret\n"
	.string "from STEVEN.$"

MossdeepCity_Text_16916F:: @ 816916F
	.string "Is it really that fun collecting\n"
	.string "rocks? I don't get it.$"

MossdeepCity_Text_1691A7:: @ 81691A7
	.string "Yeah, you think so, too! What are you\n"
	.string "supposed to do with some weird rock?$"

MossdeepCity_Text_1691F2:: @ 81691F2
	.string "Around MOSSDEEP, you can see wild\n"
	.string "WAILMER.\p"
	.string "It's called, uh...\n"
	.string "What was it now...\p"
	.string "WAI, WAI, WAI...\p"
	.string "WAILMER watching!$"

MossdeepCity_Text_169266:: @ 8169266
	.string "The island's SPACE CENTER has been\n"
	.string "launching huge rockets.$"

MossdeepCity_Text_1692A1:: @ 81692A1
	.string "I'd heard from my mates in LILYCOVE\n"
	.string "that the herd of WAILMER has\l"
	.string "disappeared.\p"
	.string "What went down over there, I wonder?$"

MossdeepCity_Text_169314:: @ 8169314
	.string "Wouldn't it be nice?\p"
	.string "If the whole world was covered in\n"
	.string "plants and flowers like this island?$"

MossdeepCity_Text_169370:: @ 8169370
	.string "All life needs the sea to live, even\n"
	.string "though it makes its home on the land.\p"
	.string "Life, having run its course, becomes\n"
	.string "soil and returns to the land.\p"
	.string "And the sea is always connected to\n"
	.string "the land.\p"
	.string "Yes, like the very shoreline here.$"

MossdeepCity_Text_16944E:: @ 816944E
	.string "A voyage on a ship is fine.\p"
	.string "But crossing the sea with POKéMON\n"
	.string "using SURF...\p"
	.string "Now that's an exhilarating trip!\n"
	.string "Wouldn't you agree, youngster?$"

MossdeepCity_Text_1694DA:: @ 81694DA
	.string "This rock has a special meaning to\n"
	.string "the people at the SPACE CENTER.\p"
	.string "They put it here as their wish for\n"
	.string "their rockets to fly safely.\p"
	.string "When you make a wish, what do you use?\n"
	.string "Do you wish upon a star?\p"
	.string "I use a wish tag to make it happen.\n"
	.string "That's what I do.$"

MossdeepCity_Text_1695D3:: @ 81695D3
	.string "It's a white rock.$"

MossdeepCity_Text_1695E6:: @ 81695E6
	.string "MOSSDEEP CITY POKéMON GYM\n"
	.string "LEADERS: LIZA & TATE\p"
	.string "“The mystic combination!”$"

MossdeepCity_Text_16962F:: @ 816962F
	.string "MOSSDEEP CITY\n"
	.string "“Our slogan: Cherish POKéMON!”$"

MossdeepCity_Text_16965C:: @ 816965C
	.string "MOSSDEEP SPACE CENTER\n"
	.string "“The closest place to space.”$"

	.else
MossdeepCity_Text_1690A9:: @ 81690A9
	.string "Ich habe das von TROY bekommen, weiß\n"
	.string "aber nicht, was ich damit machen soll.\p"
	.string "Ich glaube, es heißt KING-STEIN.\n"
	.string "Möchtest du das haben?$"

MossdeepCity_Text_169117:: @ 8169117
	.string "Warum willst du das haben?\n"
	.string "Du bist komisch.\p"
	.string "Du kannst es behalten, aber erzähle\n"
	.string "es nicht TROY.$"

MossdeepCity_Text_16916F:: @ 816916F
	.string "Macht es wirklich so viel Spaß, Steine zu\n"
	.string "sammeln? Kann ich gar nicht verstehen.$"

MossdeepCity_Text_1691A7:: @ 81691A7
	.string "Ach, du denkst das auch! Was soll man\n"
	.string "auch mit komischen Steinen anfangen?$"

MossdeepCity_Text_1691F2:: @ 81691F2
	.string "In der Nähe von MOOSBACH CITY\n"
	.string "kann man wilde WAILMER sehen.\p"
	.string "Das nennt man, äh...\n"
	.string "Nennt man... äh... ähm...\p"
	.string "WAI..., WAI..., WAI...\p"
	.string "WAILMER Watching!$"

MossdeepCity_Text_169266:: @ 8169266
	.string "Am RAUMFAHRTZENTRUM auf der Insel\n"
	.string "werden große Raketen gestartet.$"

MossdeepCity_Text_1692A1:: @ 81692A1
	.string "Ich habe von Freunden in SEEGRA-\n"
	.string "SULB gehört, dass eine Herde WAILMER\l"
	.string "verschwunden ist.\p"
	.string "Was mag da wohl passiert sein?$"

MossdeepCity_Text_169314:: @ 8169314
	.string "Wäre das nicht schön?\p"
	.string "Wenn die ganze Welt so mit Blumen und\n"
	.string "Pflanzen bewachsen wäre wie diese\l"
	.string "Insel?$"

MossdeepCity_Text_169370:: @ 8169370
	.string "Alle Lebewesen brauchen das Meer, um\n"
	.string "leben zu können, auch wenn sie an Land\l"
	.string "leben.\p"
	.string "Am Ende seiner Reise wird aus dem\n"
	.string "Lebenden Erde und er kehrt zurück\l"
	.string "zum Land.\p"
	.string "Und das Meer steht immer in Verbindung\n"
	.string "zum Land.\p"
	.string "Genau wie dieses Ufer hier.$"

MossdeepCity_Text_16944E:: @ 816944E
	.string "Eine Reise auf einem Schiff ist toll.\p"
	.string "Aber das Meer auf einem POKéMON zu\n"
	.string "überqueren, das SURFER einsetzt...\p"
	.string "Das ist wirklich eine aufregende Sache.\n"
	.string "Meinst du nicht auch, Kindchen?$"

MossdeepCity_Text_1694DA:: @ 81694DA
	.string "Dieser Felsen hat eine ganz besondere\n"
	.string "Bedeutung für das RAUMFAHRTZENTRUM.\p"
	.string "Sie haben ihn hier hingesetzt als\n"
	.string "Glücksbringer für den sicheren Flug der\l"
	.string "Raketen.\p"
	.string "Wenn du dir etwas wünschst, was machst\n"
	.string "du dann? Sternschnuppen beobachten?\p"
	.string "Ich benutze ein Wunschkärtchen.\n"
	.string "Genau das mache ich.$"

MossdeepCity_Text_1695D3:: @ 81695D3
	.string "Ein weißer Felsen.$"

MossdeepCity_Text_1695E6:: @ 81695E6
	.string "POKéMON ARENA von MOOSBACH CITY \n"
	.string "LEITER: SVENJA & BEN\p"
	.string "“Die mystische Kombination!”$"

MossdeepCity_Text_16962F:: @ 816962F
	.string "MOOSBACH CITY\n"
	.string "“Unser Motto: Liebe POKéMON!”$"

MossdeepCity_Text_16965C:: @ 816965C
	.string "MOOSBACH CITY RAUMFAHRTZENTRUM\n"
	.string "“Der letzte Ort vor dem All.”$"

	.endif
