	.ifndef GERMAN
FortreeCity_Text_167577:: @ 8167577
	.string "Sniff...\n"
	.string "Um... You, uh...smell singed.\p"
	.string "Were you at a volcano or something?$"

FortreeCity_Text_1675C2:: @ 81675C2
	.string "I want to go to the POKéMON GYM, but\n"
	.string "something's blocking the way.\p"
	.string "After all the bother I went through\n"
	.string "training on ROUTE 120...$"

FortreeCity_Text_167642:: @ 8167642
	.string "I've got my pride-and-joy POKéMON\n"
	.string "with me. This time, I'll beat WINONA.$"

FortreeCity_Text_16768A:: @ 816768A
	.string "The ground absorbs rainwater, and\n"
	.string "trees grow by drinking that water...\p"
	.string "Our FORTREE CITY exists because\n"
	.string "there's both water and soil.$"

FortreeCity_Text_16770E:: @ 816770E
	.string "The CITY consists of homes built on\n"
	.string "trees.\p"
	.string "Perhaps because of that lifestyle,\n"
	.string "everyone is healthy and lively.\p"
	.string "Why, even myself - I feel as if I've\n"
	.string "grown thirty years younger.$"

FortreeCity_Text_1677BD:: @ 81677BD
	.string "Living on top of trees is okay.\p"
	.string "But sometimes BUG POKéMON come in\n"
	.string "through windows.\l"
	.string "It can be really startling.$"

FortreeCity_Text_16782C:: @ 816782C
	.string "Some POKéMON evolve when they go\n"
	.string "through a Game Link cable.$"

FortreeCity_Text_167868:: @ 8167868
	.string "Something unseeable is in the way.$"

FortreeCity_Text_16788B:: @ 816788B
	.string "Something unseeable is in the way.\p"
	.string "Want to use the DEVON SCOPE?$"

FortreeCity_Text_1678CB:: @ 81678CB
	.string "{PLAYER} used the DEVON SCOPE.\p"
	.string "An invisible POKéMON became completely\n"
	.string "visible!\p"
	.string "The startled POKéMON fled!$"

FortreeCity_Text_16792F:: @ 816792F
	.string "FORTREE CITY\n"
	.string "“The treetop city that frolics with\l"
	.string "nature.”$"

FortreeCity_Text_167969:: @ 8167969
	.string "FORTREE CITY POKéMON GYM\n"
	.string "LEADER: WINONA\p"
	.string "“The bird user taking flight into\n"
	.string "the world.”$"

	.else
	FortreeCity_Text_167577:: @ 8167577
	.string "Schnüffel...\n"
	.string "Äh... Du, uh... riechst angesengt.\p"
	.string "Warst du auf einem Vulkan oder so?$"

FortreeCity_Text_1675C2:: @ 81675C2
	.string "Ich wollte zur POKéMON ARENA, aber\n"
	.string "irgendetwas blockiert den Weg.\p"
	.string "Und das, nachdem ich auf der ROUTE 120\n"
	.string "so fleißig trainiert habe...$"

FortreeCity_Text_167642:: @ 8167642
	.string "Dieses POKéMON ist mein ganzer Stolz!\n"
	.string "Diesmal werde ich WIBKE besiegen!$"

FortreeCity_Text_16768A:: @ 816768A
	.string "Der Boden nimmt das Regenwasser auf,\n"
	.string "die Bäume trinken es und wachsen...\p"
	.string "Unser BAUMHAUSEN CITY existiert, weil\n"
	.string "es genügend Wasser und Boden gibt.$"

FortreeCity_Text_16770E:: @ 816770E
	.string "Die STADT besteht aus Häusern, die auf\n"
	.string "Bäumen gebaut sind.\p"
	.string "Aufgrund dieser Lebensweise ist jeder\n"
	.string "hier gesund und munter.\p"
	.string "Und auch ich fühle mich, als sei ich\n"
	.string "30 Jahre jünger geworden.$"

FortreeCity_Text_1677BD:: @ 81677BD
	.string "Auf Bäumen zu leben ist klasse.\p"
	.string "Aber manchmal kommen KÄFER-POKéMON\n"
	.string "durch die Fenster herein.\l"
	.string "Das kann einen ganz schön erschrecken.$"

FortreeCity_Text_16782C:: @ 816782C
	.string "Manche POKéMON entwickeln sich, wenn\n"
	.string "sie durch ein Verbindungskabel laufen.$"

FortreeCity_Text_167868:: @ 8167868
	.string "Etwas Unsichtbares blockiert den Weg.$"

FortreeCity_Text_16788B:: @ 816788B
	.string "Etwas Unsichtbares blockiert den Weg.\p"
	.string "Willst du das DEVON-SCOPE einsetzen?$"

FortreeCity_Text_1678CB:: @ 81678CB
	.string "{PLAYER} setzt das DEVON-SCOPE ein.\p"
	.string "Ein unsichtbares POKéMON ist sichtbar\n"
	.string "geworden!\p"
	.string "Das erschrockene POKéMON flieht!$"

FortreeCity_Text_16792F:: @ 816792F
	.string "BAUMHAUSEN CITY\n"
	.string "“Die Stadt in den Baumkronen,\l"
	.string "verbrüdert mit der Natur.”$"

FortreeCity_Text_167969:: @ 8167969
	.string "POKéMON ARENA von BAUMHAUSEN CITY\n"
	.string "LEITERIN: WIBKE\p"
	.string "“Die Vogel-Liebhaberin hebt ab zum\n"
	.string "Flug in die Welt.”$"
	.endif
