	.ifndef GERMAN
ClosedSootopolisDoorText: @ 8169690
	.string "The door is closed.$"

SootopolisCity_Text_1696A4:: @ 81696A4
	.string "Who might you be?\p"
	.string "This is the CAVE OF ORIGIN.\p"
	.string "The spirits of POKéMON, becalmed at\n"
	.string "MT. PYRE, are said to be revived here.\p"
	.string "Please leave.$"

SootopolisCity_Text_16972B:: @ 816972B
	.string "Diving in the sea. Climbing up and\n"
	.string "down stairs all the time...\p"
	.string "If you live in this town, you end up\n"
	.string "getting physically fit.$"

SootopolisCity_Text_1697A7:: @ 81697A7
	.string "I... I've never been out of this city.\p"
	.string "I wonder what the world is like on the\n"
	.string "other side of this round sky?$"

SootopolisCity_Text_169813:: @ 8169813
	.string "Hm!\n"
	.string "You've come all the way to SOOTOPOLIS?\l"
	.string "You're no ordinary tourist.\p"
	.string "But I suppose that doesn't make you an\n"
	.string "extraordinary tourist, either.$"

SootopolisCity_Text_1698A0:: @ 81698A0
	.string "SOOTOPOLIS sprang up as a town in the\n"
	.string "crater of a volcano.\p"
	.string "If you look up at the sky, the lip of\n"
	.string "the crater is also visible.\l"
	.string "So, all you see is the sky in a circle.\p"
	.string "But that's what makes the sky above\n"
	.string "SOOTOPOLIS the most beautiful.$"

SootopolisCity_Text_169988:: @ 8169988
	.string "STEVEN: {PLAYER}{KUN}, you came, too?\n"
	.string "In this terrible rainstorm, yet...\p"
	.string "Oh, yes, can you hear out what my\n"
	.string "friend has to say?$"

SootopolisCity_Text_1699FD:: @ 81699FD
	.string "My name is WALLACE.\n"
	.string "I'm this town's GYM LEADER.\p"
	.string "I've also been entrusted with the\n"
	.string "protection of the CAVE OF ORIGIN.\p"
	.string "This downpour is caused by a power\n"
	.string "emanating from the CAVE OF ORIGIN.$"

SootopolisCity_Text_169AB7:: @ 8169AB7
	.string "That... That is the BLUE ORB.\p"
	.string "I see.\n"
	.string "Follow me.$"

SootopolisCity_Text_169AE7:: @ 8169AE7
	.string "STEVEN: This rain...\p"
	.string "People and POKéMON need water to live...\p"
	.string "But why does this rain fill us with\n"
	.string "so much dread?\p"
	.string "The rain clouds over SOOTOPOLIS will\n"
	.string "keep building and soon extend all\l"
	.string "over HOENN...\p"
	.string "If that were to happen...$"

SootopolisCity_Text_169BC7:: @ 8169BC7
	.string "WALLACE: The CAVE OF ORIGIN is ahead.\p"
	.string "No one from SOOTOPOLIS is permitted\n"
	.string "to enter the CAVE OF ORIGIN.\p"
	.string "But you must go.\n"
	.string "Together with your BLUE ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_169C99:: @ 8169C99
	.string "STEVEN: {PLAYER}{KUN}, I never expected you\n"
	.string "to be holding the BLUE ORB.\p"
	.string "You'll be okay. With your POKéMON,\n"
	.string "you'll get things done no matter what.\p"
	.string "I'm convinced of it!$"

SootopolisCity_Text_169D37:: @ 8169D37
	.string "WALLACE: You must go together with\n"
	.string "your BLUE ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_169DA6:: @ 8169DA6
	.string "STEVEN: You'll be okay. With your\n"
	.string "POKéMON, you'll get things done\l"
	.string "whatever happens.\p"
	.string "I'm convinced of it!$"

SootopolisCity_Text_169E0F:: @ 8169E0F
	.string "STEVEN: {PLAYER}{KUN}, you came, too?\n"
	.string "Under this scorching sun, yet...\p"
	.string "Oh, yes, can you hear out what my\n"
	.string "friend has to say?$"

SootopolisCity_Text_169E82:: @ 8169E82
	.string "My name is WALLACE.\n"
	.string "I'm this town's GYM LEADER.\p"
	.string "I've also been entrusted with the\n"
	.string "protection of the CAVE OF ORIGIN.\p"
	.string "This sunshine is caused by a power\n"
	.string "emanating from the CAVE OF ORIGIN.$"

SootopolisCity_Text_169F3C:: @ 8169F3C
	.string "That... That is the RED ORB.\p"
	.string "I see.\n"
	.string "Follow me.$"

SootopolisCity_Text_169F6B:: @ 8169F6B
	.string "STEVEN: This sunlight...\p"
	.string "People and POKéMON need sunlight\n"
	.string "to live...\p"
	.string "But why does this sunlight fill us\n"
	.string "with so much dread?\p"
	.string "The blazing sun over SOOTOPOLIS is\n"
	.string "intensifying... Soon, all of HOENN\l"
	.string "will be under its withering glare...\p"
	.string "If that were to happen...$"

SootopolisCity_Text_16A06C:: @ 816A06C
	.string "WALLACE: The CAVE OF ORIGIN is ahead.\p"
	.string "No one from SOOTOPOLIS is permitted\n"
	.string "to enter the CAVE OF ORIGIN.\p"
	.string "But you must go. \n"
	.string "Together with your RED ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_16A13E:: @ 816A13E
	.string "STEVEN: {PLAYER}{KUN}, I never expected you\n"
	.string "to be holding the RED ORB.\p"
	.string "You'll be okay. With your POKéMON,\n"
	.string "you'll get things done no matter what.\p"
	.string "I'm convinced of it!$"

SootopolisCity_Text_16A1DB:: @ 816A1DB
	.string "WALLACE: You must go together with\n"
	.string "your RED ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_16A249:: @ 816A249
	.string "STEVEN: You'll be okay. With your\n"
	.string "POKéMON, you'll get things done\l"
	.string "whatever happens.\p"
	.string "I'm convinced of it!$"

SootopolisCity_Text_16A2B2:: @ 816A2B2
	.string "The legend told by the old man on\n"
	.string "MT. PYRE... It wasn't a made-up story.$"

SootopolisCity_Text_16A2FB:: @ 816A2FB
	.string "The natural balance of HOENN is going\n"
	.string "through a wrenching shift...$"

SootopolisCity_Text_16A33E:: @ 816A33E
	.string "STEVEN: {PLAYER}{KUN}, we owe it all to you.\p"
	.string "The sky above SOOTOPOLIS has returned\n"
	.string "to normal. For that, WALLACE sends his\l"
	.string "thanks, too.\p"
	.string "And, that same WALLACE is waiting for\n"
	.string "you inside.\p"
	.string "He's strong.\n"
	.string "But the way you are now, you should be\l"
	.string "on equal footing with him.\p"
	.string "Give it your best shot.$"

SootopolisCity_Text_16A455:: @ 816A455
	.string "All life starts at the CAVE OF ORIGIN,\n"
	.string "and it all ends on MT. PYRE...\p"
	.string "Where do people and POKéMON come\n"
	.string "from? Where are we bound?$"

SootopolisCity_Text_16A4D6:: @ 816A4D6
	.string "Let me guess, you're going to challenge\n"
	.string "WALLACE?\p"
	.string "Oh, you are really?\n"
	.string "You're awfully brave!$"

SootopolisCity_Text_16A531:: @ 816A531
	.string "Let me guess, you've beaten WALLACE!\n"
	.string "Oh, you did, really?\p"
	.string "Maybe I'll become your fan!$"

SootopolisCity_Text_16A587:: @ 816A587
	.string "Hm!\n"
	.string "You've come all the way to SOOTOPOLIS?\l"
	.string "You're no ordinary tourist.\p"
	.string "But I suppose that doesn't make you an\n"
	.string "extraordinary tourist, either.$"

SootopolisCity_Text_16A614:: @ 816A614
	.string "A circle of a night sky framed by the\n"
	.string "crater of a volcano...\p"
	.string "And in that ring, stars flicker and\n"
	.string "blink as if they were alive...\l"
	.string "It's my favorite scenery.$"

SootopolisCity_Text_16A6AE:: @ 816A6AE
	.string "Hunh? Where is my house?$"

SootopolisCity_Text_16A6C7:: @ 816A6C7
	.string "SOOTOPOLIS CITY POKéMON GYM\n"
	.string "LEADER: WALLACE\p"
	.string "“Artist, and lover of WATER.”$"

SootopolisCity_Text_16A711:: @ 816A711
	.string "SOOTOPOLIS CITY\p"
	.string "“The mystical city where history\n"
	.string "slumbers.”$"

	.else
ClosedSootopolisDoorText: @ 8169690
	.string "Die Tür ist zu.$"

SootopolisCity_Text_1696A4:: @ 81696A4
	.string "Wer bist du denn wohl?\p"
	.string "Dies ist die URZEITHÖHLE.\p"
	.string "Die Geister der POKéMON, zur Ruhe\n"
	.string "gebettet am PYROBERG, erwachen\l"
	.string "hier zum Leben, sagt man.\p"
	.string "Bitte verlasse diesen Ort.$"

SootopolisCity_Text_16972B:: @ 816972B
	.string "Im Meer tauchen. Treppenstufen auf und\n"
	.string "ab rennen...\p"
	.string "Wenn du in diesem Ort lebst, wirst du\n"
	.string "körperlich fit.$"

SootopolisCity_Text_1697A7:: @ 81697A7
	.string "Ich... Ich war noch nie außerhalb der\n"
	.string "Stadt.\p"
	.string "Ich frage mich, wie die Welt hinter\n"
	.string "diesem Horizont aussieht?$"

SootopolisCity_Text_169813:: @ 8169813
	.string "Hm! Du bist den ganzen Weg nach\n"
	.string "XENEROVILLE gekommen? Du bist\l"
	.string "kein normaler Tourist.\p"
	.string "Aber das macht dich auch nicht zu einem\n"
	.string "außergewöhnlichen Touristen.$"

SootopolisCity_Text_1698A0:: @ 81698A0
	.string "XENEROVILLE entwickelte sich im Krater\n"
	.string "eines Vulkans.\p"
	.string "Wenn du in den Himmel schaust, kannst\n"
	.string "du den Rand des Kraters über dir\l"
	.string "erkennen. Der Himmel wird zum Kreis.\p"
	.string "Aber das macht den Himmel über\n"
	.string "XENEROVILLE zum schönsten Himmel.$"

SootopolisCity_Text_169988:: @ 8169988
	.string "TROY: {PLAYER}{KUN}, du bist auch hier?\n"
	.string "Bei diesem schrecklichen Regen...\p"
	.string "Oh, ja, kannst du verstehen, was mein\n"
	.string "Freund gerade sagt?$"

SootopolisCity_Text_1699FD:: @ 81699FD
	.string "Mein Name ist WASSILI.\n"
	.string "Ich bin der hiesige ARENALEITER.\p"
	.string "Ich bin auch damit beauftragt, die\n"
	.string "URZEITHÖHLE zu schützen.\p"
	.string "Diese Regenschauer werden durch eine\n"
	.string "Kraft in der Höhle verursacht.$"

SootopolisCity_Text_169AB7:: @ 8169AB7
	.string "Das... Das ist die BLAUE KUGEL.\p"
	.string "Ich verstehe.\n"
	.string "Folge mir.$"

SootopolisCity_Text_169AE7:: @ 8169AE7
	.string "TROY: Dieser Regen...\p"
	.string "Menschen und POKéMON brauchen\n"
	.string "Wasser zum Leben...\p"
	.string "Aber warum verursacht dieser Regen\n"
	.string "so viele Probleme?\p"
	.string "Immer mehr Regenwolken werden sich\n"
	.string "über XENEROVILLE bilden und sich über\l"
	.string "die ganze HOENN-Region ausbreiten.$"

SootopolisCity_Text_169BC7:: @ 8169BC7
	.string "WASSILI: Die URZEITHÖHLE ist dort\n"
	.string "drüben.\p"
	.string "Niemandem in XENEROVILLE ist es\n"
	.string "erlaubt, die URZEITHÖHLE zu betreten.\p"
	.string "Aber du musst hineingehen.\n"
	.string "Zusammen mit der BLAUEN KUGEL.\p"
	.string "Du musst gehen, egal was dich im Inneren\n"
	.string "der Höhle erwartet...$"

SootopolisCity_Text_169C99:: @ 8169C99
	.string "TROY: {PLAYER}{KUN}, ich hätte nie ver-\n"
	.string "mutet, dass du die BLAUE KUGEL bei dir\l"
	.string "hast.\p"
	.string "Dir wird nichts passieren. Mit deinen\n"
	.string "POKéMON an deiner Seite schaffst du es.\p"
	.string "Davon bin ich überzeugt!$"

SootopolisCity_Text_169D37:: @ 8169D37
	.string "WASSILI: Du musst deine BLAUE KUGEL\n"
	.string "mitnehmen.\p"
	.string "Du musst gehen, egal was dich im Inneren\n"
	.string "der HÖHLE erwartet...$"

SootopolisCity_Text_169DA6:: @ 8169DA6
	.string "TROY: Dir wird nichts passieren.\n"
	.string "Mit deinen POKéMON an deiner Seite\l"
	.string "schaffst du es.\p"
	.string "Davon bin ich überzeugt!$"

SootopolisCity_Text_169E0F:: @ 8169E0F
	.string "TROY: {PLAYER}{KUN}, du bist auch hier?\n"
	.string "Bei diesem heißen Sonnenschein...\p"
	.string "Oh, ja, kannst du verstehen, was mein\n"
	.string "Freund gerade sagt?$"

SootopolisCity_Text_169E82:: @ 8169E82
	.string "Mein Name ist WASSILI.\n"
	.string "Ich bin der hiesige ARENALEITER.\p"
	.string "Ich bin auch damit beauftragt, die\n"
	.string "URZEITHÖHLE zu schützen.\p"
	.string "Dieser Sonnenschein wird durch eine\n"
	.string "Kraft in der Höhle verursacht.$"

SootopolisCity_Text_169F3C:: @ 8169F3C
	.string "Das... Das ist die ROTE KUGEL.\p"
	.string "Ich verstehe.\n"
	.string "Folge mir.$"

SootopolisCity_Text_169F6B:: @ 8169F6B
	.string "TROY: Dieser Sonnenschein...\p"
	.string "Menschen und POKéMON brauchen\n"
	.string "Sonnenlicht zum Leben...\p"
	.string "Aber warum verursacht dieses Licht\n"
	.string "so viele Probleme?\p"
	.string "Die Sonnenstrahlen über XENEROVILLE\n"
	.string "werden immer intensiver und bald\l"
	.string "wird es in ganz HOENN zu heiß.\p"
	.string "Und wenn das passiert...$"

SootopolisCity_Text_16A06C:: @ 816A06C
	.string "WASSILI: Die URZEITHÖHLE ist dort\n"
	.string "drüben.\p"
	.string "Niemandem in XENEROVILLE ist es\n"
	.string "erlaubt, die URZEITHÖHLE zu betreten.\p"
	.string "Aber du musst hineingehen.\n"
	.string "Zusammen mit der ROTEN KUGEL.\p"
	.string "Du musst gehen, egal was dich im Inneren\n"
	.string "der Höhle erwartet...$"

SootopolisCity_Text_16A13E:: @ 816A13E
	.string "TROY: {PLAYER}{KUN}, ich hätte nie ver-\n"
	.string "mutet, dass du die ROTE KUGEL bei dir\l"
	.string "hast.\p"
	.string "Dir wird nichts passieren. Mit deinen\n"
	.string "POKéMON an deiner Seite schaffst du es.\p"
	.string "Davon bin ich überzeugt!$"

SootopolisCity_Text_16A1DB:: @ 816A1DB
	.string "WASSILI: Du musst deine ROTE KUGEL\n"
	.string "mitnehmen.\p"
	.string "Du musst gehen, egal was dich im Inneren\n"
	.string "der Höhle erwartet...$"

SootopolisCity_Text_16A249:: @ 816A249
	.string "TROY: Dir wird nichts passieren. Mit\n"
	.string "deinen POKéMON an deiner Seite\l"
	.string "schaffst du es.\p"
	.string "Davon bin ich überzeugt!$"

SootopolisCity_Text_16A2B2:: @ 816A2B2
	.string "Die Legende, die der alte Mann am PYRO-\n"
	.string "BERG erzählt hat... war kein Märchen.$"

SootopolisCity_Text_16A2FB:: @ 816A2FB
	.string "Das natürliche Gleichgewicht von HOENN\n"
	.string "verändert sich dramatisch...$"

SootopolisCity_Text_16A33E:: @ 816A33E
	.string "TROY: {PLAYER}{KUN}, dir verdanken\n"
	.string "wir alles.\p"
	.string "Der Himmel über XENEROVILLE ist\n"
	.string "wieder normal. Dafür dankt dir auch\l"
	.string "WASSILI.\p"
	.string "Und genau dieser WASSILI\n"
	.string "erwartet dich dort drinnen.\p"
	.string "Er ist stark. Aber auf dem Weg, auf dem\n"
	.string "du dich jetzt befindest, solltest du\l"
	.string "keine Probleme haben, ihn zu besiegen.\p"
	.string "Gib dein Bestes.$"

SootopolisCity_Text_16A455:: @ 816A455
	.string "Alles Leben beginnt in der URZEITHÖHLE\n"
	.string "und endet am PYROBERG...\p"
	.string "Woher kommen die Menschen und\n"
	.string "POKéMON? Wohin gehen wir?$"

SootopolisCity_Text_16A4D6:: @ 816A4D6
	.string "Lass mich raten! Du wirst WASSILI\n"
	.string "herausfordern?!?\p"
	.string "Wirklich?\n"
	.string "Du bist wirklich mutig!$"

SootopolisCity_Text_16A531:: @ 816A531
	.string "Lass mich raten! Du hast WASSILI\n"
	.string "besiegt!?! Wirklich!?!\p"
	.string "Dann werde ich vielleicht dein Fan!$"

SootopolisCity_Text_16A587:: @ 816A587
	.string "Hm! Du bist den ganzen Weg nach\n"
	.string "XENEROVILLE gekommen? Du bist\l"
	.string "kein gewöhnlicher Tourist.\p"
	.string "Aber das macht dich auch nicht zu einem\n"
	.string "außergewöhnlichen Touristen.$"

SootopolisCity_Text_16A614:: @ 816A614
	.string "Ein Stück des Nachthimmels, umgeben\n"
	.string "vom Rund des Vulkankraters...\p"
	.string "Und in diesem runden Stück Himmel\n"
	.string "strahlen und blinken die Sterne, als\l"
	.string "wären sie lebendig. Ich liebe das...$"

SootopolisCity_Text_16A6AE:: @ 816A6AE
	.string "Huch! Wo ist mein Haus?$"

SootopolisCity_Text_16A6C7:: @ 816A6C7
	.string "POKéMON ARENA von XENEROVILLE\n"
	.string "LEITER: WASSILI\p"
	.string "“Künstler und Liebhaber des WASSERS.”$"

SootopolisCity_Text_16A711:: @ 816A711
	.string "XENEROVILLE\p"
	.string "“Die mystische Stadt, in der die\n"
	.string "Geschichte stillsteht.”$"

	.endif
