	.ifndef GERMAN
LittlerootTown_Text_16A7C9:: @ 816A7C9
	.string "MOM: {PLAYER}, we're here, honey!\p"
	.string "It must be tiring riding with our things\n"
	.string "in the moving truck.\p"
	.string "Well, this is LITTLEROOT TOWN.\p"
	.string "How do you like it?\n"
	.string "This is our new home!\p"
	.string "It has a quaint feel, but it seems to be\n"
	.string "an easy place to live, don't you think?\p"
	.string "And, you get your own room, {PLAYER}!\n"
	.string "Let's go inside.$"

LittlerootTown_Text_16A8EE:: @ 816A8EE
	.string "MOM: Wait, {PLAYER}!$"

LittlerootTown_Text_16A8FD:: @ 816A8FD
	.string "MOM: {PLAYER}! {PLAYER}! Did you\n"
	.string "introduce yourself to PROF. BIRCH?\p"
	.string "Oh! What an adorable POKéMON!\n"
	.string "You got it from PROF. BIRCH. How nice!\p"
	.string "You're your father's child, all right.\n"
	.string "You look good together with POKéMON!\p"
	.string "Here, honey! If you're going out on an\n"
	.string "adventure, wear these RUNNING SHOES.\p"
	.string "They'll put a zip in your step!$"

LittlerootTown_Text_16AA32:: @ 816AA32
	.string "{PLAYER} switched shoes with the\n"
	.string "RUNNING SHOES.$"

LittlerootTown_Text_16AA5C:: @ 816AA5C
	.string "MOM: {PLAYER}, those shoes came with\n"
	.string "instructions.\p"
	.string "“Press the B Button while wearing these\n"
	.string "RUNNING SHOES to run extra-fast!\p"
	.string "“Slip on these RUNNING SHOES and race\n"
	.string "in the great outdoors!”$"

LittlerootTown_Text_16AB10:: @ 816AB10
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "To think that you have your very own\n"
	.string "POKéMON now...\l"
	.string "Your father will be overjoyed.\p"
	.string "...But please be careful.\n"
	.string "If anything happens, you can come home.\p"
	.string "Go on, go get them, honey!$"

LittlerootTown_Text_16AC00:: @ 816AC00
	.string "If you use a PC, you can store items\n"
	.string "and POKéMON.\p"
	.string "The power of science is staggering!$"

LittlerootTown_Text_16AC56:: @ 816AC56
	.string "PROF. BIRCH spends days in his LAB\n"
	.string "studying, then he'll suddenly go out in\l"
	.string "the wild to do more research...\p"
	.string "When does PROF. BIRCH spend time\n"
	.string "at home?$"

LittlerootTown_Text_16ACEB:: @ 816ACEB
	.string "If you go in the tall grass at the sides\n"
	.string "of this road, wild POKéMON will appear.$"

LittlerootTown_Text_16AD3C:: @ 816AD3C
	.string "It's not safe to go out there if you\n"
	.string "don't have any POKéMON with you.$"

LittlerootTown_Text_16AD82:: @ 816AD82
	.string "I can hear someone shouting down the\n"
	.string "road here.\p"
	.string "What should I do? What should we do?\n"
	.string "Somebody has to go help...$"

LittlerootTown_Text_16ADF2:: @ 816ADF2
	.string "Boy, am I glad you went and rescued\n"
	.string "the PROFESSOR.$"

LittlerootTown_Text_16AE25:: @ 816AE25
	.string "Are you going to catch POKéMON?\n"
	.string "Good luck!$"

LittlerootTown_Text_16AE50:: @ 816AE50
	.string "LITTLEROOT TOWN\n"
	.string "“A town that can't be shaded any hue.”$"

LittlerootTown_Text_16AE87:: @ 816AE87
	.string "PROF. BIRCH'S POKéMON LAB$"

LittlerootTown_Text_16AEA1:: @ 816AEA1
	.string "{PLAYER}'s HOUSE$"

LittlerootTown_Text_16AEAC:: @ 816AEAC
	.string "PROF. BIRCH'S HOUSE$"

	.else
LittlerootTown_Text_16A7C9:: @ 816A7C9
	.string "MUTTER: {PLAYER}, wir sind da, Schatz!\p"
	.string "Die Fahrt im Umzugswagen zwischen all\n"
	.string "unseren Sachen war bestimmt ermüdend.\p"
	.string "Nun, wir sind in WURZELHEIM.\p"
	.string "Wie gefällt es dir?\n"
	.string "Dies ist unser neues Zuhause!\p"
	.string "Ist das idyllisch! Man kann hier sicher\n"
	.string "wunderbar leben, meinst du nicht?\p"
	.string "Und... Du bekommst dein eigenes\n"
	.string "Zimmer, {PLAYER}! Lass uns hineingehen!$"

LittlerootTown_Text_16A8EE:: @ 816A8EE
	.string "MUTTER: Warte, {PLAYER}!$"

LittlerootTown_Text_16A8FD:: @ 816A8FD
	.string "MUTTER: {PLAYER}! Hast du dich schon\n"
	.string "PROF. BIRK vorgestellt?\p"
	.string "Oh! Was für ein hübsches POKéMON! Du\n"
	.string "hast es von PROF. BIRK erhalten? Toll!\p"
	.string "Du bist das Kind deines Vaters! Wunder-\n"
	.string "bar. Du siehst gut aus mit deinem\l"
	.string "POKéMON!\p"
	.string "Hier, Liebling! Für eine Abenteuerreise\n"
	.string "sind diese TURBOTRETER wie geschaffen.\p"
	.string "Sie werden deinen Schritt\n"
	.string "beschleunigen!$"

LittlerootTown_Text_16AA32:: @ 816AA32
	.string "{PLAYER} zieht die TURBOTRETER an.$"

LittlerootTown_Text_16AA5C:: @ 816AA5C
	.string "MUTTER: {PLAYER}, für diese Schuhe gibt\n"
	.string "es eine Bedienungsanleitung.\p"
	.string "“Halte den B-Knopf gedrückt,\n"
	.string "wenn du diese TURBOTRETER anhast,\l"
	.string "um zu rennen!\p"
	.string "Schlüpf in diese TURBOTRETER und\n"
	.string "erobere die Welt da draußen!”$"

LittlerootTown_Text_16AB10:: @ 816AB10
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Sich vorzustellen, dass du nun dein\n"
	.string "eigenes POKéMON besitzt...\l"
	.string "Dein Vater wird überglücklich sein.\p"
	.string "...Aber sei bitte vorsichtig.\n"
	.string "Sollte etwas passieren, komm wieder\l"
	.string "nach Hause.\p"
	.string "Lauf, schnapp' sie dir alle, Schatz!$"

LittlerootTown_Text_16AC00:: @ 816AC00
	.string "Wenn du einen PC benutzt, kannst du\n"
	.string "dort Items und POKéMON lagern.\p"
	.string "Die Kraft der Wissenschaft ist\n"
	.string "atemberaubend!$"

LittlerootTown_Text_16AC56:: @ 816AC56
	.string "PROF. BIRK verbringt seine Tage in\n"
	.string "seinem LABOR, dann rennt er plötzlich\l"
	.string "nach draußen in die Wildnis, um zu\l"
	.string "forschen...\p"
	.string "Wann ist PROF. BIRK eigentlich mal\n"
	.string "zu Hause?$"

LittlerootTown_Text_16ACEB:: @ 816ACEB
	.string "Wenn du in das hohe Gras am Seitenrand\n"
	.string "der Pfade gehst, triffst du auf\l"
	.string "wilde POKéMON.$"

LittlerootTown_Text_16AD3C:: @ 816AD3C
	.string "Hast du keine POKéMON dabei, ist es\n"
	.string "dort sehr gefährlich.$"

LittlerootTown_Text_16AD82:: @ 816AD82
	.string "Ich kann am Ende dieser Straße\n"
	.string "jemanden schreien hören.\p"
	.string "Was soll ich tun? Was sollen wir tun?\n"
	.string "Jemand muss doch helfen...$"

LittlerootTown_Text_16ADF2:: @ 816ADF2
	.string "Junge, bin ich froh, dass du den\n"
	.string "PROFESSOR gerettet hast!$"

LittlerootTown_Text_16AE25:: @ 816AE25
	.string "Gehst du POKéMON fangen?\n"
	.string "Viel Glück!$"

LittlerootTown_Text_16AE50:: @ 816AE50
	.string "WURZELHEIM\n"
	.string "“Ein Ort, wie es ihn nur einmal gibt.”$"

LittlerootTown_Text_16AE87:: @ 816AE87
	.string "PROF. BIRKS POKéMON-LABOR$"

LittlerootTown_Text_16AEA1:: @ 816AEA1
	.string "HAUS von {PLAYER}$"

LittlerootTown_Text_16AEAC:: @ 816AEAC
	.string "PROF. BIRKS HAUS$"

	.endif
